### ISSUE TITLE
[Empire of the Sun (2nd Edition)] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11840] opened 2022-12-27 06:15 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [73262 bytes](https://vassalengine.org/files/gh/766ebc2eed563d76cd46063f528bb8b438f0716a) |

<pre>?????????????

Empire of the Sun (2nd Edition) v5.10.2.1 3.6.9

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 03:46
Duplicate of #5813

**Closed by BrentEaston** 2023-01-07 03:46 UTC
Labels: ABR
