### ISSUE TITLE
[Warhammer Underworlds Mod] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13048] opened 2024-01-09 00:48 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [1174642 bytes](https://vassalengine.org/files/gh/383373a6b941468d730cd610dfb2485f55cea9cf) |

<pre>

Warhammer Underworlds Mod v9.2 3.7.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2024-01-15 10:20
Duplicate of #5813

**Closed by BrentEaston** 2024-01-15 10:20 UTC
Labels: ABR
