### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11461] opened 2022-05-23 03:48 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [5627 bytes](https://vassalengine.org/files/gh/a518a2cfc061f60deeba4905a2f7c82cbc1c55dc) |

<pre>I have no idea
I have to say that sometimes, the chrome also crashes saying that there are not enough memory
Which should be wrong because the PC seems to be working ok

3.6.6

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by riverwanderer** [comment] 2022-09-28 04:54
Duplicate of https://github.com/vassalengine/vassal/issues/11408.

**Closed by riverwanderer** 2022-09-28 04:54 UTC
Labels: ABR
