### ISSUE TITLE
[Unnamed module] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "this.crc" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12894] opened 2023-11-09 23:06 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | jjtaylor37@yahoo.com |
| Error Log | [7827 bytes](https://vassalengine.org/files/gh/0afed5b37d456f697e74dd4ca2c9f198aca6cbc2) |

<pre>opening VASL

Unnamed module v0.0 3.7.5

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "this.crc" is null
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "this.crc" is null
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 02:46
Duplicate of #12558

**Closed** 2024-01-08 23:32 UTC
Labels: bug
