### ISSUE TITLE
[Unconditional Surrender!] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\USE Map-WEST&EASTUPDT2022.jpg:0,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12550] opened 2023-08-09 22:06 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | leo.delauncey@live.com |
| Error Log | [196543 bytes](https://vassalengine.org/files/gh/45034f47aad8853e8e9a66ef5e25f21972dc73c7) |

<pre>Zoomed out of map in Poland scenario playing solitaire

Unconditional Surrender! v2.3.5.3 3.6.19

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\USE Map-WEST&EASTUPDT2022.jpg:0,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment] 2024-01-25 23:13
Duplicate of #10937

**Closed by BrentEaston** 2024-01-25 23:13 UTC
Labels: ABR
