### ISSUE TITLE
[Flying Colors] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13282] opened 2024-04-18 02:32 UTC
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter |  |
| Error Log | [23433 bytes](https://vassalengine.org/files/gh/4ac9b3882b002a8ef58a22103a27eae2e7b2cfd0) |

<pre>Marking damages to a ship.
Don't know how to make it again.

Flying Colors v2.6.0 3.7.10

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2577)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:274)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:248)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:25
Duplicate of #12033

**Closed by BrentEaston** 2024-07-16 06:25 UTC
Labels: ABR
