### ISSUE TITLE
[Blue Water Navy] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11440] opened 2022-05-13 22:31 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | daorvaz@gmail.com |
| Error Log | [83431 bytes](https://vassalengine.org/files/gh/d713dc4fc32ff3e5c317e6670906e1867ed12f8c) |

<pre>

Blue Water Navy v1.12 3.6.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:37
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:37 UTC
Labels: ABR
