### ISSUE TITLE
[BCS_Gazala] IllegalStateException: Component must have a valid peer

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11875] opened 2023-01-09 00:51 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [7748 bytes](https://vassalengine.org/files/gh/be8943455651bf338e64edc8bd05b11191aae002) |

<pre>Edit "Moved marker"

BCS_Gazala vv0.1 3.6.9

java.lang.IllegalStateException: Component must have a valid peer
 at java.desktop/java.awt.Component$FlipBufferStrategy.flipSubRegion(Component.java:4181)
 at java.desktop/java.awt.Component$FlipBufferStrategy.showSubRegion(Component.java:4305)
 at java.desktop/java.awt.Component$FlipSubRegionBufferStrategy.showIfNotLost(Component.java:4602)
 at java.desktop/javax.swing.BufferStrategyPaintManager.show(BufferStrategyPaintManager.java:208)
</pre>

**Comment by BrentEaston** [comment] 2023-01-09 21:54
Duplicate of #11389

**Closed by BrentEaston** 2023-01-09 21:54 UTC
Labels: ABR
