### ISSUE TITLE
[Malifaux 3e] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11947] opened 2023-02-01 16:08 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [8654 bytes](https://vassalengine.org/files/gh/d1bc311d4df6a06eb8f63780ed8cbf0a5a0613cd) |

<pre>

Malifaux 3e vMoM_v4a 3.6.10

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-02-01 22:46
Duplicate of #11561

**Closed by BrentEaston** 2023-02-01 22:46 UTC
Labels: ABR
