### ISSUE TITLE
[Skies Above the Reich] NullPointerException: Cannot invoke "String.isEmpty()" because "currentTitle" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11811] opened 2022-12-07 01:15 UTC
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter | rarubin79@gmail.com |
| Error Log | [10572 bytes](https://vassalengine.org/files/gh/67f631c6261d6c26abb99da720cd2819624d8edd) |

<pre>Well here I am again! I pretty much tried to reproduce my previous bug, and I did. All the previous steps were followed. The Counters tabbed view is showing, and I believe this time, I clicked the "Time" tab, and then the "General Markers" tab. (it is possible I clicked one in between these two).

Have fun,
Rich Rubin

Skies Above the Reich v1.01 3.6.8

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "currentTitle" is null
 at VASSAL.build.widget.TabWidget.refreshTabs(TabWidget.java:116)
 at VASSAL.build.widget.TabWidget.getComponent(TabWidget.java:136)
 at VASSAL.build.widget.TabWidget.stateChanged(TabWidget.java:55)
 at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:446)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:09
Duplicate of #11810

**Closed by BrentEaston** 2023-01-07 23:09 UTC
Labels: ABR
