### ISSUE TITLE
[NAPOLEON CONQUEST] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11864] opened 2023-01-07 16:33 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [12127 bytes](https://vassalengine.org/files/gh/a9a2be916e482180af057e717ba8691e37c6b818) |

<pre>

NAPOLEON CONQUEST v0.0.1 3.6.9

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null
 at VASSAL.counters.Decorator.getOutermost(Decorator.java:525)
 at VASSAL.build.widget.PieceSlot.getLocalizedConfigureName(PieceSlot.java:609)
 at VASSAL.build.Widget$MyCellRenderer.getListCellRendererComponent(Widget.java:183)
 at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1444)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 22:21
Duplicate of #11813

**Closed by BrentEaston** 2023-01-07 22:21 UTC
Labels: ABR
