### ISSUE TITLE
[VSQL] NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12957] opened 2023-12-02 15:14 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [10573 bytes](https://vassalengine.org/files/gh/eb65c52d54572d093078132d017c9e2aee20f4dd) |

<pre>

VSQL v4.3.7 3.7.5

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:265)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:247)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 00:39
Duplicate of #12494

**Closed by BrentEaston** 2023-12-09 00:39 UTC
Labels: ABR
