### ISSUE TITLE
[Malifaux 3e] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11265] opened 2022-03-03 17:09 UTC
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter |  |
| Error Log | [211172 bytes](https://vassalengine.org/files/gh/7d91d30b3aa89e2aea3fd77b24de7b9284af2380) |

<pre>

Malifaux 3e v3e Malifaux Burns V3d 3.6.5

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:14
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:14 UTC
Labels: ABR
