### ISSUE TITLE
Loading VASL maps not possible w/ v. 3.6.1?

### ISSUE THREAD

**Issue by pablogons** [vassalengine/vassal#10884] opened 2021-12-04 11:58 UTC
When trying to load either a VASL Scenario Setup module or a board from the repository, an error message shows up: 

"Board missing. Your board configuration must match X by X row/column matrix. Use NUL or NULV boards if required"

**Comment by uckelman** [comment] 2021-12-04 12:08
You're seeing an incompatibility between VASL and Vassal 3.6. There's already a fix for it, but the new version of VASL which was intended to contain that fix was released without it. 

See here for details:  http://www.gamesquad.com/forums/index.php?threads/vasl-patch.165946/#post-2076775

There should be a _new_ fix release soon.

**Closed by uckelman** 2021-12-04 12:08 UTC

**Comment by uckelman** [comment] 2021-12-04 13:41
There's a new download at vasl.info for 6.6.3.1 now, which fixes the problem.

**Comment by pablogons** [comment] 2021-12-05 12:35
It's working fine now! Thank you so much for your prompt feedback and your immediate action to fix the issue.
