### ISSUE TITLE
[Bitter Woods - Designer Edition] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11940] opened 2023-01-28 19:09 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter | mgmitch100@yahoo.com |
| Error Log | [26055 bytes](https://vassalengine.org/files/gh/959b9f34aa096b25796ab66704f4f564b3eb55d2) |

<pre>after cycling thru my opponents move it prompted me do I want to start a new log file when I click yes a bug appears sayinf this was created by an earlier version,

Bitter Woods - Designer Edition v2.6 3.6.10

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
 at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
 at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
 at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
</pre>

**Comment by BrentEaston** [comment] 2023-02-01 22:45
Duplicate of #11939

**Closed by BrentEaston** 2023-02-01 22:45 UTC
Labels: ABR
