### ISSUE TITLE
ExecutionException: java.io.IOException: Cannot delete file: C:\Users\USER PC\AppData\Local\VASSAL\tiles\e1d1509cc8ae8514b50a6e8e6159e8b9e9ff3df6

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11357] opened 2022-04-11 04:08 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [19149 bytes](https://vassalengine.org/files/gh/cf47692cc2d4d83020b27f7d23044da0fb44d9f8) |

<pre>

3.6.6

java.util.concurrent.ExecutionException: java.io.IOException: Cannot delete file: C:\Users\USER PC\AppData\Local\VASSAL\tiles\e1d1509cc8ae8514b50a6e8e6159e8b9e9ff3df6
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 18:46
Duplicate of #10627

**Closed by Cattlesquat** 2023-02-10 18:46 UTC
Labels: ABR
