### ISSUE TITLE
ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11604] opened 2022-07-19 22:45 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | segarraef@hotmail.com |
| Error Log | [5633 bytes](https://vassalengine.org/files/gh/2c8b573260bddf01b9bf31a0f5fa5c136ca6f22f) |

<pre>No open Holland 44

3.6.7

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 02:59
Duplicate of #11240

**Closed by BrentEaston** 2023-01-08 02:59 UTC
Labels: ABR
