### ISSUE TITLE
[Washington's War] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11956] opened 2023-02-06 02:31 UTC
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter | mgmitch100@yahoo.com |
| Error Log | [8032 bytes](https://vassalengine.org/files/gh/60031dc4e4369fcb5ac6e76c862c556c8e713499) |

<pre>Can not save files with3.6.11

Washington's War v2.0 3.6.11

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
 at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
 at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
 at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
</pre>

**Comment by BrentEaston** [comment] 2023-02-08 00:52
Duplicate of #11939

**Closed by BrentEaston** 2023-02-08 00:52 UTC
Labels: ABR
