### ISSUE TITLE
[Into the Woods] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11307] opened 2022-03-24 17:15 UTC
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | jm.cross@live.co.uk |
| Error Log | [8172 bytes](https://vassalengine.org/files/gh/6541ea93dc67ba21f54f2c450dbc3adb105adaa8) |

<pre>Trying to open Into the Woods on Vassal for the 1st time. 

Into the Woods v1.02 3.6.5

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:289)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:15
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:15 UTC
Labels: ABR
