### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12476] opened 2023-07-17 11:53 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [5052 bytes](https://vassalengine.org/files/gh/fe60c04116864312437888a2c1802e391a5cf52d) |

<pre>Fresh install of Twilight Struggle module (3.1), and just trying to start the module (had a warning about deprecated APIs being used).

Twilight Struggle 3.1 v3.1.2 3.6.19

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2023-07-18 21:20
Duplicate of #11874

**Closed by BrentEaston** 2023-07-18 21:20 UTC
Labels: ABR
