### ISSUE TITLE
[The Last Gamble] NullPointerException: Cannot read field "parent" because "comp" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13211] opened 2024-03-18 11:11 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter |  |
| Error Log | [16188 bytes](https://vassalengine.org/files/gh/015406c728d5355ceb5a488b154ec21ba15f1669) |

<pre>Deleting redundent maps all in one tab

The Last Gamble vK11 3.7.9

java.lang.NullPointerException: Cannot read field "parent" because "comp" is null
 at java.desktop/java.awt.Container.remove(Container.java:1290)
 at VASSAL.build.widget.MapWidget.remove(MapWidget.java:104)
 at VASSAL.configure.ConfigureTree.remove(ConfigureTree.java:1379)
 at VASSAL.configure.ConfigureTree.delete(ConfigureTree.java:1371)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:23
Duplicate of #12290

**Closed by BrentEaston** 2024-07-15 23:23 UTC
Labels: ABR
