### ISSUE TITLE
[VSQL] NullPointerException: Cannot invoke "CASL.Map.GameMap.onMap(int, int)" because "this.CASLMap" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12449] opened 2023-07-07 08:22 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | shaughn_haines@yahoo.com |
| Error Log | [102085 bytes](https://vassalengine.org/files/gh/fcbba9623c1a21ec1452d670b57f7c2a01c482b3) |

<pre>VASSAL v3.6.19 - VSQL v4.3.5
I was attempting to use the LOS tool (2 clicks, translucent counters). I haven't been able to reproduce the error.

VSQL v4.3.5 3.6.19

java.lang.NullPointerException: Cannot invoke "CASL.Map.GameMap.onMap(int, int)" because "this.CASLMap" is null
 at VASL.build.module.map.CASLThread.mousePressed(CASLThread.java:336)
 at VASSAL.build.module.Map.mousePressed(Map.java:1930)
 at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
 at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
</pre>

**Comment by BrentEaston** [comment] 2023-07-08 23:14
Duplicate of #12449

**Closed by BrentEaston** 2023-07-08 23:14 UTC
Labels: ABR
