### ISSUE TITLE
[VSQL] NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12395] opened 2023-06-23 18:29 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | shanefgale@gmail.com |
| Error Log | [14378 bytes](https://vassalengine.org/files/gh/2d863b3700412510a944ea798f54ddbb875802a9) |

<pre>Playing The Guards Counterattack solo. Turn 1 - Axis PFPh.

In the Turn 1 Axis PFPh, a stack of 3 units and a leader in hex H5 fired upon 3 Allied(Russian) units in the open and upon a roll of 1,1 recieved a KIA result. I dragged a box around the stack of 3 Allied counters and right clicked and chose Graveyard. The Uncaught Exception error then occurred.

VSQL v4.3.5 3.6.19

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:264)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:246)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-07-26 07:00
Duplicate of #12494

**Closed by BrentEaston** 2023-07-26 07:00 UTC
Labels: ABR
