### ISSUE TITLE
[Bitter Woods - Designer Edition] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11984] opened 2023-02-11 21:29 UTC
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter | mgmitch100@yahoo.com |
| Error Log | [25463 bytes](https://vassalengine.org/files/gh/da5d852ada816d93a76a56c401e0f1efb1976887) |

<pre>I was in Vassal Buldge game and simple advanced thru his turn and when the prompt showed up doi I want to staart a new file  a bug  erro shows up. It will not let me save at all.

Bitter Woods - Designer Edition v2.6 3.6.11

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
 at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
 at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
 at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
</pre>

**Comment by BrentEaston** [comment] 2023-02-11 21:44
Duplicate of #11939

**Closed by BrentEaston** 2023-02-11 21:45 UTC
Labels: ABR
