### ISSUE TITLE
[Afrika Korps] InvalidPathException: Illegal char <:> at index 13: odds_marker_1:1.png

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13363] opened 2024-06-06 02:11 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | madvitale@gmail.com |
| Error Log | [61689 bytes](https://vassalengine.org/files/gh/3f7443314007e42f82a1fdc9434627a0f7b07bed) |

<pre>Afrika Korps 2.1-ch.vmod. Following tutorial. Chose 'More Information', and it errored out.

Afrika Korps v2.1 3.7.12

java.nio.file.InvalidPathException: Illegal char <:> at index 13: odds_marker_1:1.png
 at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
 at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
 at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
 at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:03
Duplicate of #13313

**Closed by BrentEaston** 2024-07-15 23:03 UTC
Labels: ABR
