### ISSUE TITLE
[Warhammer Underworlds Mod] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12758] opened 2023-09-28 14:04 UTC
| ABR | |
|-----|-----|
| Version | 3.7.1 |
| Reporter |  |
| Error Log | [2192581 bytes](https://vassalengine.org/files/gh/f64d3df7c7e9a214c44c78b3b6ef3f7a2749c54c) |

<pre>

Warhammer Underworlds Mod v8.1.5 3.7.1

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-10-02 01:51
Duplicate of #5813

**Closed by BrentEaston** 2023-10-02 01:51 UTC
Labels: ABR
