### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12991] opened 2023-12-14 02:31 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | cavan.cunningham@outlook.com |
| Error Log | [7797 bytes](https://vassalengine.org/files/gh/d71175b79dca673c70b5099730f29bf6919f82a7) |

<pre>starting module. in Vassal 3.7.5

Twilight Struggle 3.1 v3.1.2 3.7.5

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2023-12-14 09:18
Duplicate of #11874

**Closed by BrentEaston** 2023-12-14 09:18 UTC
Labels: Bug in Custom Code
