### ISSUE TITLE
ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11605] opened 2022-07-19 23:03 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | segarraef@hotmail.com |
| Error Log | [4203 bytes](https://vassalengine.org/files/gh/7e01fea50f36a8997a5df86a2e5777a118a9d5fe) |

<pre>

3.6.7

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:38
Duplicate of #11604

**Closed by BrentEaston** 2023-01-07 23:38 UTC
Labels: ABR
