### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13328] opened 2024-05-11 17:00 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | pongpanotcshop@gmail.com |
| Error Log | [4171 bytes](https://vassalengine.org/files/gh/e96bfcc892162525e2e5272454d70957d2f15ac5) |

<pre>just open vassal and this dialog appeared

3.7.12

java.lang.ExceptionInInitializerError: null
 at VASSAL.launch.ModuleManager.launch(ModuleManager.java:384)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 22:35
Duplicate of #12999

**Closed by BrentEaston** 2024-07-16 22:35 UTC
Labels: ABR
