### ISSUE TITLE
ExecutionException: java.io.IOException: Cannot delete file: C:\Users\admin\AppData\Local\VASSAL\tiles\1f724b1214e7b87bcf21fe46fe5d5c2bf31ce773

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11247] opened 2022-02-23 10:51 UTC
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter |  |
| Error Log | [63280 bytes](https://vassalengine.org/files/gh/060429d6f48f86ee2800ab908254b53523713f0a) |

<pre>

3.6.5

java.util.concurrent.ExecutionException: java.io.IOException: Cannot delete file: C:\Users\admin\AppData\Local\VASSAL\tiles\1f724b1214e7b87bcf21fe46fe5d5c2bf31ce773
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:508)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 18:46
Duplicate of #10627

**Closed by Cattlesquat** 2023-02-10 18:46 UTC
Labels: ABR
