### ISSUE TITLE
ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13285] opened 2024-04-20 18:56 UTC
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter |  |
| Error Log | [4221 bytes](https://vassalengine.org/files/gh/4708f6609d4134cab6a4fe0e696217281c0c66e1) |

<pre>

3.7.10

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:32
Duplicate of #11240

**Closed by BrentEaston** 2024-07-16 06:32 UTC
Labels: ABR
