### ISSUE TITLE
[Eldritch Horror] NoSuchMethodError: 'void foobarius.HoldableDecorator.setOldProperties()'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11672] opened 2022-09-03 17:33 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [9670 bytes](https://vassalengine.org/files/gh/9e940e29707741a8afc149571ef38fc7575c0392) |

<pre>

Eldritch Horror v1.9.1 3.6.7

java.lang.NoSuchMethodError: 'void foobarius.HoldableDecorator.setOldProperties()'
 at foobarius.HoldableDecorator.followHolder(HoldableDecorator.java:239)
 at foobarius.HolderDecorator.myKeyEvent(HolderDecorator.java:135)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:492)
 at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:165)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 03:16
Duplicate of #11268

**Closed by BrentEaston** 2023-01-08 03:16 UTC
Labels: ABR
