### ISSUE TITLE
[TLNB: La Souffel - Rapp's Last Stand] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12658] opened 2023-09-06 13:40 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [40754 bytes](https://vassalengine.org/files/gh/418852a91250bb82f1c0ccc4c0f27b715aafb5e5) |

<pre>Introducir mi nombre

TLNB: La Souffel - Rapp's Last Stand vv1.43 (X)_NLC 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-09-06 23:14
Duplicate of #5813

**Closed** 2023-09-06 23:16 UTC
Labels: ABR
