### ISSUE TITLE
ExecutionException: java.lang.IllegalStateException: bad type: 91

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11966] opened 2023-02-08 03:31 UTC
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter | james.sterrett@gmail.com |
| Error Log | [44205 bytes](https://vassalengine.org/files/gh/4097c75a696f1976c85b269e92280914d1e29fc3) |

<pre>Loading OWS Ukraine v3.6 module; stopped at "Tiling images"

3.6.11

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: bad type: 91
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-09 21:11
Duplicate of #11413

**Closed by Cattlesquat** 2023-02-09 21:11 UTC
Labels: ABR
