### ISSUE TITLE
[Commands & Colors: Napoleonics] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11625] opened 2022-08-06 17:03 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | davidandvicki@msn.com |
| Error Log | [16597 bytes](https://vassalengine.org/files/gh/694f7adf99b60e18776f89e788590f7a86363608) |

<pre>Just closing the C&C Nap 4.1.1 mod

Commands & Colors: Napoleonics v4.1.1 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
 at VASSAL.build.module.GameState$12.compare(GameState.java:1456)
 at VASSAL.build.module.GameState$12.compare(GameState.java:1442)
 at java.base/java.util.TimSort.binarySort(TimSort.java:296)
 at java.base/java.util.TimSort.sort(TimSort.java:239)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:16
Duplicate of #11299

**Closed by BrentEaston** 2023-01-07 23:16 UTC
Labels: ABR
