### ISSUE TITLE
[Twilight Struggle] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getShape()" because "piece" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12712] opened 2023-09-16 02:03 UTC
| ABR | |
|-----|-----|
| Version | 3.7.0 |
| Reporter |  |
| Error Log | [20420 bytes](https://vassalengine.org/files/gh/91af7c19e25c45c81884a35326aadc67d9e915a0) |

<pre>played first round of Twilight Struggle 3.0.11 version

Twilight Struggle v3.0.11 3.7.0

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getShape()" because "piece" is null
 at VASSAL.build.module.map.CounterDetailViewer.getBounds(CounterDetailViewer.java:814)
 at VASSAL.build.module.map.CounterDetailViewer.fixBounds(CounterDetailViewer.java:663)
 at VASSAL.build.module.map.CounterDetailViewer.drawGraphics(CounterDetailViewer.java:375)
 at ca.mkiefte.CardZoomer.drawGraphics(CardZoomer.java:53)
</pre>

**Comment by BrentEaston** [comment] 2023-09-18 04:02
Duplicate of #11874

**Closed by BrentEaston** 2023-09-18 04:02 UTC
Labels: ABR
