### ISSUE TITLE
[CG Carrier Battle: Philippine Sea] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12103] opened 2023-03-17 13:45 UTC
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter | rdmorss@morssweb.com |
| Error Log | [4852 bytes](https://vassalengine.org/files/gh/d1858520e29883c433174297868411700c156df1) |

<pre>Map window toolbar Button icon. - click select - then click Cancel on the file selector == EEK 

CG Carrier Battle: Philippine Sea v 3.6.14

java.lang.NullPointerException: null
 at java.base/java.io.File.<init>(File.java:278)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.filenameFilterCallback(GtkFileDialogPeer.java:107)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.run(Native Method)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.showNativeDialog(GtkFileDialogPeer.java:195)
</pre>

**Comment by BrentEaston** [comment] 2023-04-19 03:44
Duplicate of #12115

**Closed by BrentEaston** 2023-04-19 03:44 UTC
Labels: ABR
