### ISSUE TITLE
[Commands & Colors: Napoleonics V5] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13200] opened 2024-03-13 12:12 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | markben61@gmail.com |
| Error Log | [25441 bytes](https://vassalengine.org/files/gh/298e40190ee5c950079253fa7b46dd3a44d007c7) |

<pre>Deleted a Global Property from a couple of maps that was duplicated at Module level. Then rolled back through the logfile and progressed replay to the point where the Global Property was referenced.

Log file replayed the action fine.

Error occurred when I clicked on one of the relevant pieces. Around same time an unrelated mouse-over was triggered.

Commands & Colors: Napoleonics V5 v5.0.0a121 3.7.9

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2577)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:277)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:251)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:25
Duplicate of #12033

**Closed by BrentEaston** 2024-07-16 06:25 UTC
Labels: ABR
