### ISSUE TITLE
[Pacific War 2] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11675] opened 2022-09-04 13:57 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [10086 bytes](https://vassalengine.org/files/gh/3f9396eea529fd11f7bef65fa882ff685bd9b641) |

<pre>

Pacific War 2 v2.00.024 3.6.7

java.lang.NullPointerException: null
 at VASSAL.script.ExpressionInterpreter.evaluate(ExpressionInterpreter.java:272)
 at VASSAL.script.expression.BeanShellExpression.evaluate(BeanShellExpression.java:65)
 at VASSAL.script.expression.Expression.tryEvaluate(Expression.java:211)
 at VASSAL.script.expression.Expression.tryEvaluate(Expression.java:136)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 19:46
Duplicate of #11887

**Closed** 2023-02-10 19:47 UTC
Labels: ABR
