### ISSUE TITLE
[Which Witch Is Which] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\ShoppingMapBackground.png:0,6@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13184] opened 2024-02-27 17:01 UTC
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter |  |
| Error Log | [14778 bytes](https://vassalengine.org/files/gh/f52d46d2375417fe5b8581c8365c960211332b6f) |

<pre>Zooming out

Which Witch Is Which v0.0 3.7.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\ShoppingMapBackground.png:0,6@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:326)
</pre>

**Comment by BrentEaston** [comment] 2024-02-28 09:04
Duplicate of #13100

**Closed by BrentEaston** 2024-02-28 09:04 UTC
Labels: ABR
