### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11165] opened 2022-02-02 08:56 UTC
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter | segarraef@hotmail.com |
| Error Log | [2668 bytes](https://vassalengine.org/files/gh/415441f5e3ad9d4ca246ffa8ea74807769c904a9) |

<pre>

3.6.4

java.lang.reflect.InvocationTargetException: null
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1369)
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1344)
 at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
 at VASSAL.launch.StartUp.initUIProperties(StartUp.java:107)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 03:01
Duplicate of #11240

**Closed by BrentEaston** 2023-01-08 03:01 UTC
Labels: ABR
