### ISSUE TITLE
[Fortress Europa (AH)] IllegalStateException: No state for trait=label;76,130;Label;8;0,0,0;255,255,255;b;0;c;0;t;c;$pieceName$ ($label$);Serif;1;0;TextLabel;;false

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13235] opened 2024-03-27 12:25 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | zovs66@gmail.com |
| Error Log | [1000123 bytes](https://vassalengine.org/files/gh/0564f28c9fe89bedf787aa25cf73ebffe06822bf) |

<pre>Trying to open up the scenario that had the previously reported cloning bug. This is bummer!

Fortress Europa (AH) v1.5 3.7.9

java.lang.IllegalStateException: No state for trait=label;76,130;Label;8;0,0,0;255,255,255;b;0;c;0;t;c;$pieceName$ ($label$);Serif;1;0;TextLabel;;false
 at VASSAL.counters.Decorator.setState(Decorator.java:444)
 at VASSAL.counters.Decorator.setState(Decorator.java:441)
 at VASSAL.counters.Decorator.setState(Decorator.java:441)
 at VASSAL.command.AddPiece.executeCommand(AddPiece.java:55)
</pre>

**Comment by BrentEaston** [comment] 2024-07-24 00:01
Duplicate of #13234

**Closed by BrentEaston** 2024-07-24 00:01 UTC
Labels: ABR
