### ISSUE TITLE
[Commands & Colors: Napoleonics V5] NoSuchMethodException: VASSAL.build.module.properties.ScenarioPropertiesOptionTab$TextConfig.<init>()

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13525] opened 2024-08-09 14:22 UTC
| ABR | |
|-----|-----|
| Version | 3.7.13 |
| Reporter | markben61@gmail.com |
| Error Log | [10440 bytes](https://vassalengine.org/files/gh/34fdd91fb73bf8c5bdab24b9b7c46152c37c1470) |

<pre>During a search (editor), on finding a match in Scenario Options.

Commands & Colors: Napoleonics V5 v5.1.0a206 3.7.13

java.lang.NoSuchMethodException: VASSAL.build.module.properties.ScenarioPropertiesOptionTab$TextConfig.<init>()
 at java.base/java.lang.Class.getConstructor0(Class.java:3784)
 at java.base/java.lang.Class.getConstructor(Class.java:2452)
 at VASSAL.configure.AutoConfigurer.createConfigurer(AutoConfigurer.java:200)
 at VASSAL.configure.AutoConfigurer.<init>(AutoConfigurer.java:87)
</pre>

**Comment by BrentEaston** [comment] 2024-08-14 22:02
Duplicate of #13509

**Closed by BrentEaston** 2024-08-14 22:02 UTC
Labels: ABR
