### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11881] opened 2023-01-09 20:11 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [5970 bytes](https://vassalengine.org/files/gh/5dafa9f03f0010b7ea9c0866779a4383dc267bb3) |

<pre>I opened my first ever module, "Twilight-Struggle-3.2.1.vmod". No idea how to keep this from happening again. 

Twilight Struggle 3.1 v3.1.2 3.6.9

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2023-01-09 21:39
Duplicate of #11874

**Closed** 2023-01-09 21:39 UTC
Labels: ABR
