### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11857] opened 2023-01-06 23:11 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter | ppenza@aol.com |
| Error Log | [23909 bytes](https://vassalengine.org/files/gh/18d58a70021de69138783ce7e98b0a7a28314c30) |

<pre>Each time I try to open the module A Time for Trumpets v2.7 it stops at 48% and this dialog appear.

3.6.9

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:23
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:23 UTC
Labels: ABR
