### ISSUE TITLE
[Combat Commander: Europe] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13042] opened 2024-01-05 17:31 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [70398 bytes](https://vassalengine.org/files/gh/72bb7649c5ca18148c0dd8b4cb031b28d052cec0) |

<pre>

Combat Commander: Europe v2.4 3.7.6

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2576)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:273)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:247)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:25
Duplicate of #12033

**Closed by BrentEaston** 2024-07-16 06:25 UTC
Labels: ABR
