### ISSUE TITLE
Deck Empty Hotkey fired by remote clients when adding first card to deck

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#6195] opened 2021-06-28 17:59 UTC
| Bugzilla |  |
|----------|----------|
| ID | BZ4300 |
| Reported | 2012-02-22 05:22:00 +0100 |
| Modified | 2013-07-28 03:49:45 +0200 |
| Product | VASSAL |
| Component | Player |
| Version | 3.1.18 |
| Platform | PC |
| OS | All |
| Status | ASSIGNED |
| Resolution | None |
| Priority | high |
| Severity | normal |
| Milestone | 3.2.9 |
| Reporter | [Seth Gilchrist](mailto:irishwulf@gmail.com) |
| Assignee | [Brent Easton](mailto:b.easton@exemail.com.au) |
| CC | b.easton@exemail.com.au, stefanotine@gmail.com, uckelman@nomic.net |

| Attachments | |
|-------|-------|
| [errorLog_P1](http://www.vassalengine.org/files/bz/3580) | [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-02-22 05:22:00 +0100 text/plain 11044 Debug statements follow setProperty() calls and commands sent to/received from server by Player 1 |

| [errorLog_P2](http://www.vassalengine.org/files/bz/3581) | [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-02-22 05:23:00 +0100 text/plain 11618 Debug statements follow setProperty() calls and commands sent to/received from server by Player 2 |

| [RTDTest.vmod](http://www.vassalengine.org/files/bz/3582) | [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-02-22 05:24:00 +0100 application/x-zip-compressed 9138 Demo module |

#### [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-02-22 05:22:52 +0100
<pre>Created attachment 3580
Debug statements follow setProperty() calls and commands sent to/received from server by Player 1

Also see forum thread:
http://www.vassalengine.org/forum/viewtopic.php?f=3&t=4927#p31178

When adding a card to a deck with either Return to Deck or Send to Location, the numPieces trait is first set to 1, then 0, then 1 again - and the Deck Empty Hotkey is fired in the middle.  Furthermore, the order of execution of the hotkey relative to other traits in a single command sequence is not consistent between the local (firing) client and the remote client.  Attached are a sample vmod, and debug statements for P1 and P2 in the following scenario:
1 - P1 checks the value of Counter using the toolbar button
2 - P2 checks the value of Counter using the toolbar button
3 - P1 selects the 'Return to Deck' context menu entry of testPiece
4 - P1 checks the value of Counter using the toolbar button
5 - P2 checks the value of Counter using the toolbar button

-Seth</pre>

#### [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-02-22 05:23:57 +0100
<pre>Created attachment 3581
Debug statements follow setProperty() calls and commands sent to/received from server by Player 2</pre>

#### [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-02-22 05:24:42 +0100
<pre>Created attachment 3582
Demo module</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2012-03-04 17:53:14 +0100
<pre>Is this reproducible in 3.1.18 as well?</pre>

#### [Seth Gilchrist](mailto:irishwulf@gmail.com) 2012-03-04 18:51:43 +0100
<pre>(In reply to comment #3)
> Is this reproducible in 3.1.18 as well?

It is present in 3.1.17, at least.</pre>

#### [Brent Easton](mailto:b.easton@exemail.com.au) 2012-07-27 04:55:46 +0200
<pre>possibly the same bug as 4302</pre>

**Comment by Cattlesquat** [comment] 2021-11-18 21:11
I ran through this bug-demo module in 3.6 and was not able to reproduce the effects. I even put a breakpoint on the deck out-of-cards thing to see if it was getting fired extra times.

However there is some stuff where deck properties could be getting oddly rearranged, so I'm making a PR to address that.

**Comment by Cattlesquat** [comment] 2021-11-18 21:13
Closed as no longer reproducible

**Closed by Cattlesquat** 2021-11-18 21:13 UTC
Labels: Not Reproducible
