### ISSUE TITLE
[Warhammer Underworlds Mod] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11916] opened 2023-01-22 12:51 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter | livid13@gmail.com |
| Error Log | [966282 bytes](https://vassalengine.org/files/gh/06263211b5dc4f639683bc4823838e404cf002c9) |

<pre>

Warhammer Underworlds Mod v7.1 3.6.10

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-25 11:03
Duplicate of #11561

**Closed by BrentEaston** 2023-01-25 11:03 UTC
Labels: ABR
