### ISSUE TITLE
[Heights of Courage] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12806] opened 2023-10-12 20:24 UTC
| ABR | |
|-----|-----|
| Version | 3.7.2 |
| Reporter |  |
| Error Log | [12273 bytes](https://vassalengine.org/files/gh/93579f48a667d187c2f81ac74e2339513ff1d574) |

<pre>

Heights of Courage v1.0 3.7.2

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-10-18 23:37
Duplicate of #5813

**Closed by BrentEaston** 2023-10-18 23:37 UTC
Labels: ABR
