### ISSUE TITLE
[Star Wars: Imperial Assault] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12583] opened 2023-08-17 05:28 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [351936 bytes](https://vassalengine.org/files/gh/f620c3654ee8c8d66dddc4f968f57fcd80b622d4) |

<pre>

Star Wars: Imperial Assault v1.13 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-08-21 03:01
duplicate of #5813

**Closed by BrentEaston** 2023-08-21 03:01 UTC
Labels: ABR
