### ISSUE TITLE
ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12987] opened 2023-12-12 20:35 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | gochualda@outlook.es |
| Error Log | [925530 bytes](https://vassalengine.org/files/gh/7ebb614070bc26cddb24c2f57e71db496d16704f) |

<pre>Opening Vassal WARHAMMER UNDERWORLDS MOD 9.1

3.7.5

java.util.concurrent.ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2023-12-13 20:03
Duplicate of #12987

**Closed by BrentEaston** 2023-12-13 20:03 UTC
Labels: ABR
