### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12577] opened 2023-08-16 14:10 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | ebeintides@yahoo.com |
| Error Log | [6082 bytes](https://vassalengine.org/files/gh/baaa5ebc42a58f29be29af82bb8d2b5159c2b7c4) |

<pre>opening vassal save file

3.6.19

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:519)
</pre>

**Comment by BrentEaston** [comment] 2023-08-21 03:11
Duplicate of #12346

**Closed by BrentEaston** 2023-08-21 03:11 UTC
Labels: ABR
