### ISSUE TITLE
[Blood Bowl VASSAL] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12665] opened 2023-09-07 04:05 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [21250 bytes](https://vassalengine.org/files/gh/83ac6fda73b150202ee180c115eff66a52ab12f6) |

<pre>

Blood Bowl VASSAL v1.6 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-09-08 01:53
Duplicate of #5813

**Closed by BrentEaston** 2023-09-08 01:53 UTC
Labels: ABR
