### ISSUE TITLE
Set Piece Property fails (not gracefully) in local (current piece) use

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12555] opened 2023-08-10 05:38 UTC
Build: 3.7.0-SNAPSHOT-e9cf7c2-beta-CountMapLocationIssue

Configured this SPP on a piece:

<img width="1569" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/f746c9aa-f2d3-4ab4-8658-b7a23ae7509d">

On triggering the "ROLL" key command, Vassal dumps this exception:

```
2023-08-10 06:33:03,414 [13536-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.boardPicker.board.MapGrid.getMaxPixelsPerRangeUnit(java.awt.Point)" because the return value of "VASSAL.build.module.map.boardPicker.Board.getGrid()" is null
	at VASSAL.build.module.Map.getMaxPixelsPerRangeUnit(Map.java:1220)
	at VASSAL.build.module.index.VassalMapPieceIndex.getPieces(VassalMapPieceIndex.java:137)
	at VASSAL.build.module.index.IndexManager.getPieces(IndexManager.java:149)
	at VASSAL.build.module.index.IndexManager.getPieces(IndexManager.java:153)
	at VASSAL.build.module.index.IndexManager.getPieces(IndexManager.java:164)
	at VASSAL.counters.GlobalCommand.apply(GlobalCommand.java:620)
	at VASSAL.counters.SetPieceProperty.myKeyEvent(SetPieceProperty.java:314)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:517)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.TriggerAction.doLoopOnce(TriggerAction.java:326)
	at VASSAL.counters.TriggerAction.myKeyEvent(TriggerAction.java:202)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:165)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.ReportState.keyEvent(ReportState.java:125)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:519)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:164)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.Decorator.keyEvent(Decorator.java:518)
	at VASSAL.counters.GlobalCommandVisitor.apply(GlobalCommandVisitor.java:136)
	at VASSAL.counters.GlobalCommandVisitor.apply(GlobalCommandVisitor.java:115)
	at VASSAL.counters.GlobalCommandVisitor.visitDefault(GlobalCommandVisitor.java:110)
	at VASSAL.counters.PieceVisitorDispatcher.accept(PieceVisitorDispatcher.java:46)
	at VASSAL.counters.DeckVisitorDispatcher.accept(DeckVisitorDispatcher.java:37)
	at VASSAL.counters.GlobalCommand.apply(GlobalCommand.java:828)
	at VASSAL.build.module.GlobalKeyCommand.apply(GlobalKeyCommand.java:73)
	at VASSAL.build.module.map.MassKeyCommand.lambda$new$0(MassKeyCommand.java:155)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by BrentEaston** [comment] 2023-08-11 11:48
Caused by using Set Piece Property on a Map with no grid. Fixed in current GKC-Parameters branch

**Closed** 2023-08-14 22:55 UTC
Labels: bug, Reproducible, Beta
