### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12000] opened 2023-02-13 12:45 UTC
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter | pgde69@gmail.com |
| Error Log | [33324 bytes](https://vassalengine.org/files/gh/465da8686ae192f6b2f358e0239e5ea96c110020) |

<pre>just loading the module, during the loading of the resources

3.6.11

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-17 21:01
Duplicate of #11912

**Closed by Cattlesquat** 2023-02-17 21:01 UTC
Labels: ABR
