### ISSUE TITLE
[Unnamed module] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11809] opened 2022-12-06 13:43 UTC
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter | asd |
| Error Log | [9963 bytes](https://vassalengine.org/files/gh/02457ea51fa507ab2cee808d3d79ed85b6adcee2) |

<pre>

Unnamed module v0.0 3.6.8

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 03:46
Duplicate of #5813

**Closed by BrentEaston** 2023-01-07 03:46 UTC
Labels: ABR
