### ISSUE TITLE
[Dragon Pass] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12280] opened 2023-05-04 13:45 UTC
| ABR | |
|-----|-----|
| Version | 3.6.17 |
| Reporter |  |
| Error Log | [11535 bytes](https://vassalengine.org/files/gh/e803894f8fc89e2969c64a0bc27c02558c0fb083) |

<pre>Just logging in

Dragon Pass v0.3 3.6.17

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-05-10 04:30
Duplicate of #5813

**Closed by BrentEaston** 2023-05-10 04:30 UTC
Labels: ABR
