### ISSUE TITLE
[Flying Colors] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13258] opened 2024-04-07 14:00 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | nhills@gmail.com |
| Error Log | [46024 bytes](https://vassalengine.org/files/gh/35556eb8888eb82738e18fe9d7b09e2eb87c5bd7) |

<pre>Starting tutorial  in Flying Colours 2.6.0 as observer

Flying Colors v2.6.0 3.7.9

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 22:25
Duplicate of #13339

**Closed by BrentEaston** 2024-07-16 22:25 UTC
Labels: ABR
