### ISSUE TITLE
[Twilight Struggle NRE] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11873] opened 2023-01-08 14:01 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter | 1023471019@QQ.COM |
| Error Log | [89740 bytes](https://vassalengine.org/files/gh/7abacac3d6eb5e364e704ade5b8e6540e493b6af) |

<pre>??

Twilight Struggle NRE v1.0.2 3.6.9

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 22:30
Duplicate of #11561

**Closed by BrentEaston** 2023-01-08 22:30 UTC
Labels: ABR
