### ISSUE TITLE
ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13245] opened 2024-04-01 01:17 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter |  |
| Error Log | [35313 bytes](https://vassalengine.org/files/gh/83b7a17cb83eb5c44d92a0714746222fca4770e1) |

<pre>

3.7.9

java.util.concurrent.ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-04-13 05:41
Duplicate of #12292

**Closed by BrentEaston** 2024-04-13 05:41 UTC
Labels: ABR
