### ISSUE TITLE
ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13299] opened 2024-04-28 14:10 UTC
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter |  |
| Error Log | [26582 bytes](https://vassalengine.org/files/gh/38de9d555c5edfdbd6a7cb15bbfbdf6c3bda3d52) |

<pre>

3.7.10

java.util.concurrent.ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 22:57
Duplicate of #12292

**Closed by BrentEaston** 2024-07-15 22:57 UTC
Labels: ABR
