### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12805] opened 2023-10-12 13:52 UTC
| ABR | |
|-----|-----|
| Version | 3.7.2 |
| Reporter | 2328138169@qq.com |
| Error Log | [11017 bytes](https://vassalengine.org/files/gh/a1c169356a8a3f1f401164df64622331caf3b88f) |

<pre>

3.7.2

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2023-10-18 23:42
Duplicate of #12803

**Closed by BrentEaston** 2023-10-18 23:42 UTC
Labels: ABR
