### ISSUE TITLE
[Eldritch Horror] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13255] opened 2024-04-05 18:25 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | mi1291@gmail.com |
| Error Log | [11793 bytes](https://vassalengine.org/files/gh/5eb9772c49a2b43d553ab7d49d86f947853b86f7) |

<pre>game setup in editor expansion mode

Eldritch Horror v1.0 3.7.9

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null
 at VASSAL.build.module.map.SetupStack.setup(SetupStack.java:274)
 at VASSAL.build.module.map.DrawPile.setup(DrawPile.java:1227)
 at VASSAL.build.module.GameState.setup(GameState.java:566)
 at VASSAL.build.module.GameState$8.actionPerformed(GameState.java:273)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:33
Duplicate of #12869

**Closed by BrentEaston** 2024-07-16 06:33 UTC
Labels: ABR
