### ISSUE TITLE
[Malifaux 3e] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11352] opened 2022-04-08 16:58 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [211705 bytes](https://vassalengine.org/files/gh/26856d8da8900085a6d117232a3a2567bc907531) |

<pre>

Malifaux 3e v3e Malifaux Burns V3d 3.6.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:15
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:15 UTC
Labels: ABR
