### ISSUE TITLE
[TSWW Editor] NullPointerException: Cannot invoke "VASSAL.build.module.PrototypesContainer.addDefinition(VASSAL.build.module.PrototypeDefinition)" because "protos" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11841] opened 2022-12-27 18:59 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [73328 bytes](https://vassalengine.org/files/gh/e535a9ef03226cf7adfa5aec60b0c8555e1fe4e4) |

<pre>copied a folder containing several prototypes -- did not get to the point of pasting -- error occurs immediately upon copying

TSWW Editor v1.7T5 3.6.9

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.PrototypesContainer.addDefinition(VASSAL.build.module.PrototypeDefinition)" because "protos" is null
 at VASSAL.build.module.folder.PrototypeFolder.add(PrototypeFolder.java:37)
 at VASSAL.build.Builder.build(Builder.java:83)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
 at VASSAL.configure.ConfigureTree$5.actionPerformed(ConfigureTree.java:664)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:21
Duplicate of #11748

**Closed by BrentEaston** 2023-01-07 23:21 UTC
Labels: ABR

**Comment by BrentEaston** [comment] 2023-01-08 02:34
To reproduce: In any module, create a folder in the prototypes container and add some prototypes. Select and copy the folder, and then try an paste it into the prototypes container.
