### ISSUE TITLE
[Vijayanagara] ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13204] opened 2024-03-16 21:17 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | bcallen56@yahoo.com |
| Error Log | [5918 bytes](https://vassalengine.org/files/gh/8d57304281bcf1e933e226ee87a82cb21113e38a) |

<pre>Playing a vlog file.

Happened in the previous version of Vassal and happened again once I installed the newest version.  Occurred at the same spot in the playing of the vlog file both times.

Vijayanagara v1.0 3.7.9

java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
 at VASSAL.build.module.SpecialDiceButton.setFormat(SpecialDiceButton.java:224)
 at VASSAL.build.module.SpecialDiceButton$ShowResults.executeCommand(SpecialDiceButton.java:644)
 at VASSAL.command.Command.execute(Command.java:61)
 at VASSAL.build.module.BasicLogger.step(BasicLogger.java:360)
</pre>

**Comment by BrentEaston** [comment] 2024-04-12 22:48
Duplicate of #13203

**Closed by BrentEaston** 2024-04-12 22:48 UTC
Labels: ABR
