### ISSUE TITLE
[La Bataille de Quatre Bras] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13043] opened 2024-01-06 12:56 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [20895 bytes](https://vassalengine.org/files/gh/6e933923ca9a2f911e64fbd8e6138633d138f31e) |

<pre>

La Bataille de Quatre Bras v2.3 3.7.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2024-01-15 10:20
Duplicate of #5813

**Closed by BrentEaston** 2024-01-15 10:20 UTC
Labels: ABR
