### ISSUE TITLE
[Battle Spirits [Online Battlers]] IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13056] opened 2024-01-11 18:53 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [12094 bytes](https://vassalengine.org/files/gh/76804493ec281fc85d6295a33760b3ed3b02b685) |

<pre>

Battle Spirits [Online Battlers] v1.0 3.7.6

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
 at java.base/java.util.Objects.checkIndex(Objects.java:385)
</pre>

**Comment by BrentEaston** [comment] 2024-01-15 10:22
Duplicate of #12981
Fixed in 3.7.7

**Closed by BrentEaston** 2024-01-15 10:22 UTC
Labels: ABR
