### ISSUE TITLE
ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12794] opened 2023-10-08 21:46 UTC
| ABR | |
|-----|-----|
| Version | 3.7.1 |
| Reporter |  |
| Error Log | [25612 bytes](https://vassalengine.org/files/gh/e0f76ffe620b060e0ee7989c9582455bb32288f6) |

<pre>

3.7.1

java.util.concurrent.ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 02:26
Duplicate of #12292

**Closed by BrentEaston** 2023-12-09 02:26 UTC
Labels: ABR
