### ISSUE TITLE
[Commands & Colors Ancients] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12584] opened 2023-08-18 10:22 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | markben61@gmail.com |
| Error Log | [10437 bytes](https://vassalengine.org/files/gh/0183ff918972fc44aa34dbd6c4bfb87dd7e8d92b) |

<pre>Playing through a log file (in the Editor). Clicked on a card on the main board.

Commands & Colors Ancients v4.3.10 3.6.19

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2522)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:272)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:246)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 02:14
Duplicate of #12033

**Closed by BrentEaston** 2023-12-09 02:14 UTC
Labels: ABR
