### ISSUE TITLE
ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13112] opened 2024-01-28 15:05 UTC
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter |  |
| Error Log | [4186 bytes](https://vassalengine.org/files/gh/8d2155ea45d1d74b443d3a999c58f016fd0ea6c5) |

<pre>loading up the engine

3.7.7

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:32
Duplicate of #11240

**Closed by BrentEaston** 2024-07-16 06:32 UTC
Labels: ABR
