### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11944] opened 2023-01-30 21:37 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [46707 bytes](https://vassalengine.org/files/gh/687c828f4c6c50506f8a4d6d363756648ba1b365) |

<pre>

Twilight Struggle 3.1 v3.1.2 3.6.10

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2023-01-31 20:25
Duplicate of #11874

**Closed by BrentEaston** 2023-01-31 20:25 UTC
Labels: ABR
