### ISSUE TITLE
[Pax Renaissance (Solo)] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "piece1" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11954] opened 2023-02-05 02:21 UTC
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter | stan@hilinski.net |
| Error Log | [9711 bytes](https://vassalengine.org/files/gh/fc403982ff6d7744ba46a7261d1792f7280e3ef4) |

<pre>I started running a module for the first time that has a block of new and untested setup code. It will be extremely difficult for me to characterize the problem at this time. I'm going to investigate now, and perhaps I can learn more. Sorry.

Pax Renaissance (Solo) v4.1 3.6.11

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "piece1" is null
 at VASSAL.build.module.map.deck.SortParameterComparator.compare(SortParameterComparator.java:52)
 at VASSAL.build.module.map.deck.SortParameterComparator.compare(SortParameterComparator.java:28)
 at java.base/java.util.TimSort.binarySort(TimSort.java:296)
 at java.base/java.util.TimSort.sort(TimSort.java:221)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-09 21:09
Duplicate of #11955 which contains more detail

**Closed by Cattlesquat** 2023-02-09 21:09 UTC
Labels: ABR
