### ISSUE TITLE
[Battle Spirits [Online Battlers]] IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11504] opened 2022-06-13 15:27 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [24945 bytes](https://vassalengine.org/files/gh/458e1f1d4cab1424df1fdf7491f6500f01265dc9) |

<pre>

Battle Spirits [Online Battlers] v1.0 3.6.7

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
 at java.base/java.util.Objects.checkIndex(Objects.java:359)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 05:42
Duplicate of #11520

**Closed by BrentEaston** 2023-01-08 05:42 UTC
Labels: ABR
