### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12815] opened 2023-10-14 13:13 UTC
| ABR | |
|-----|-----|
| Version | 3.7.2 |
| Reporter | 2328138169@qq.com |
| Error Log | [11374 bytes](https://vassalengine.org/files/gh/2cf82506e54ecc1ddb17d41ff0827d12f2ba75a9) |

<pre>

3.7.2

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2023-10-18 23:42
Duplicate of #12803

**Closed by BrentEaston** 2023-10-18 23:42 UTC
Labels: ABR
