### ISSUE TITLE
ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12416] opened 2023-06-27 16:45 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [23839 bytes](https://vassalengine.org/files/gh/c1af78cd52491d6ba877c0c8bc30941331b3a99f) |

<pre>

3.6.19

java.util.concurrent.ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:519)
</pre>

**Comment by uckelman** [comment] 2023-06-27 17:33
Here's the problem:  MaxHeapLimit=512

The user set the limit for the tiler to something so low that it can't work.

**Comment by BrentEaston** [comment] 2023-09-05 06:27
Duplicate of #12292

**Closed by BrentEaston** 2023-09-05 06:27 UTC
Labels: ABR
