### ISSUE TITLE
ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 134

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12479] opened 2023-07-19 19:09 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | tchebuslabus@gmail.com |
| Error Log | [16717 bytes](https://vassalengine.org/files/gh/e06f8cf0b722f259a36d50971b095f23674ab02b) |

<pre>opened a skies above the britin module
Only one instance is run

3.6.19

java.util.concurrent.ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 134
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:519)
</pre>

**Comment by BrentEaston** [comment] 2023-09-01 12:24
Duplicate of #12292

**Closed by BrentEaston** 2023-09-01 12:24 UTC
Labels: ABR
