### ISSUE TITLE
Very slow editing (or even scrolling past) pieces with lots of properties since 3.7.5

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#12995] opened 2023-12-16 18:56 UTC
I've got a piece with roughly 1,000 properties. I know this isn't ideal, but it has generally worked fine. When I switched to version 3.7.5 (on OS X), VASSAL took a minute or more to open this piece. Scrolling through the piece was slow, and seemed to get slower as I moved down the list of properties. For that matter, just clicking on or moving over this piece in the editor (using the arrow keys) brings VASSAL to a halt.

I switched to OpenJDK 11, and the problem persisted.

I saved the module in 3.7.5 and restarted VASSAL, but the problem persisted.

I switched to 3.7.6 and the problem persisted.

I reverted to 3.7.4 and things are fine.

**Comment by uckelman** [comment] 2023-12-16 19:18
Where can we see the module involved?

**Comment by assaultdoor** [comment] 2023-12-16 20:49
https://drive.google.com/file/d/1gjYNCiUuZFgsmk5xlRj-Q6q0V1DdXQ7F/view?usp=drive_link

The worst offender that I noticed is under Hidden Palette > Pieces > Spirit setup components > spirit panel relay

**Comment by assaultdoor** [comment] 2023-12-16 21:27
A very basic module is here: https://drive.google.com/file/d/1INa58oVZIXmujaCtPjYDQ3ZjIiguul8z/view?usp=sharing

Try the piece "testing" in the at-start stack on the main map. It's got about 600 copies of the basic Delete property.

**Comment by riverwanderer** [comment] 2023-12-17 00:00
I suspect that PR #12861 - line numbering - is responsible.  It's working fine for me on pieces with up to 100 traits but the small overhead probably adds up. Modifying the demo, It's ok but starting to slow over 300 traits on my old MacBook. The example of 700+ traits is fairly unusable. Curiously, even selecting the piece takes forever at that number of traits.

Confirmed that the same operations are instantaneous with Vassal v3..7.4.

Paradoxically, the change actually helps with long trait lists, as Search can now give you line number references (just released in v3.7.6).  I wonder if there's a way to improve the efficiency of the line numbering but then again, a piece or prototype with 300+ traits may have other issues.

**Comment by BrentEaston** [comment] 2023-12-17 22:07
My suspicion would be that it is the use of html in the cell renderer. First test is to try just getting rid of the html and span tags and just have the line number in the default text.

**Comment by riverwanderer** [comment] 2023-12-18 11:03
> My suspicion would be that it is the use of html in the cell renderer. First test is to try just getting rid of the html and span tags and just have the line number in the default text.

I had high hopes on this too. Especially as by removing the html I could also remove the HTML exclusion routine that you have to encapsulate the data with, once html is possible.

Reverting to plain text has made no difference - as far as I can tell, not even an incremental improvement to the module. So, if the HTML string concatenation isn't causing the problem per-se, then it implies that line number concatenation on its own is also not the cause. Something more fundamental within the logic, perhaps. I'll investigate further.

New observations - scrolling, selecting and using the move up/down buttons all perform badly. Using the page up/down buttons scrolls at reasonable (normal?) speed.

**Comment by riverwanderer** [comment] 2023-12-18 11:27
Stripping the renderer back (almost) to basics also makes no difference. Below, for info only.

Further observation; performance gets worse as one scrolls further into the long list of traits.

```
    public Component getListCellRendererComponent(
      JList list, Object value, int index, boolean selected, boolean hasFocus) {

      // DO NOT pass value to super.getListCellRendererComponent()
      // It is incredibly inefficient for GamePieces and is not needed
      // since we overwrite the label text anyway.
      super.getListCellRendererComponent(list, "", index, selected, hasFocus);

//      final int lineOffset = definer.isPrototype() ? 1 : 0;
//      final int lineno = index + lineOffset;

      if (value instanceof EditablePiece) {
        final EditablePiece editableValue = (EditablePiece) value;

        // Prototype? Skip first (dummy) item to avoid outputting a blank line
        if (index > 0) {
          // For Pieces, bump index to 1
          // Special formatting for Comments
          if ((editableValue.getType().startsWith(Comment.ID))) {
            setText("<html>. <b>/* " + ConfigureTree.noHTML((editableValue.getDescription())) + " */</html>");
          }
          else {
            setText(editableValue.getDescription()); // removed ConfigureTree.noHTML() wrap for performance
          }
        }
      }
      else {
        // FIXME: When does this get used ? Assumed that prototype might have to be skipped here also.
//        final String s = value.getClass().getName();
//        setText(cellText(lineno, s.substring(s.lastIndexOf('.') + 1)));
      }
      return this;
    }
```
  }

**Comment by uckelman** [comment] 2023-12-18 13:12
This is a thing where you will want to bisect, to find exactly the commit which caused the change.

**Comment by BrentEaston** [comment] 2023-12-18 21:34
The problem is this line:

`if ((editableValue.getType().startsWith(Comment.ID))) {`

EditableValue.getType() does a full recursive drill down through all pieces in the Stack from that piece down. so it gets worse the further you are down the list.

You need to be calling Decorator.myGetType() instead which just gets the type for the specific decorator only.

**Comment by riverwanderer** [comment] 2023-12-19 01:18
> EditableValue.getType() does a full recursive drill down through all pieces in the Stack from that piece down. so it gets worse the further you are down the list.
> 
> You need to be calling Decorator.myGetType() instead which just gets the type for the specific decorator only.

Thanks @BrentEaston - indeed that makes all the difference. I've submitted the PR again.

**Comment by riverwanderer** [comment] 2023-12-19 01:27
@assaultdoor - Thanks for the report.... I think the issue is fixed; would you mind trying the MacOS build that you will find [here](https://vassalengine.org/builds/list?page=1&filter=VASSAL-3.7.7-SNAPSHOT-1308eec-12995).

**Comment by assaultdoor** [comment] 2023-12-19 02:17
I can edit that piece now! I *think* there's a tiny bit of lag as I scroll past that using the up/down arrows, but I could just be imagining that. Even if I'm right, it's not very much.

**Closed** 2024-01-08 23:48 UTC
Labels: bug
