### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11829] opened 2022-12-17 14:59 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [31545 bytes](https://vassalengine.org/files/gh/8ecad7b68ae36724fd6f3a7f11cff6b50bf6898e) |

<pre>

3.6.9

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:23
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:23 UTC
Labels: ABR
