### ISSUE TITLE
[Downtown] RuntimeException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class VASSAL.build.GameModule cannot be cast to class VASSAL.build.module.properties.GlobalPropertiesContainer (VASSAL.build.GameModule and VASSAL.build.module.properties.GlobalPropertiesContainer are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12725] opened 2023-09-19 21:10 UTC
| ABR | |
|-----|-----|
| Version | 3.7.0 |
| Reporter |  |
| Error Log | [234492 bytes](https://vassalengine.org/files/gh/51e3dc9818d5f62e0fc58546006d87ee33d0e363) |

<pre>

Downtown vv-E3.00(beta1 - build 20) 3.7.0

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class VASSAL.build.GameModule cannot be cast to class VASSAL.build.module.properties.GlobalPropertiesContainer (VASSAL.build.GameModule and VASSAL.build.module.properties.GlobalPropertiesContainer are in unnamed module of loader 'app')
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class VASSAL.build.GameModule cannot be cast to class VASSAL.build.module.properties.GlobalPropertiesContainer (VASSAL.build.GameModule and VASSAL.build.module.properties.GlobalPropertiesContainer are in unnamed module of loader 'app')
</pre>

**Comment by BrentEaston** [comment] 2023-09-19 23:48
Duplicate of #12460

**Closed by BrentEaston** 2023-09-19 23:48 UTC
Labels: ABR
