### ISSUE TITLE
[Mysterium] IllegalComponentStateException: component must be showing on the screen to determine its location

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12014] opened 2023-02-16 19:09 UTC
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter |  |
| Error Log | [787205 bytes](https://vassalengine.org/files/gh/aabe19649caabe81bc78f031a911afb824fa84f4) |

<pre>drawing every card from mysterium, detective club and 11 different editions of dixit at once from the same deck, in total probably 700-800+ cards using the draw multiple cards option

Mysterium v0.6 3.6.11

java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
 at java.desktop/java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2113)
 at java.desktop/java.awt.Component.getLocationOnScreen(Component.java:2087)
 at java.desktop/sun.lwawt.macosx.CDropTargetContextPeer.isEventInsideTarget(CDropTargetContextPeer.java:138)
 at java.desktop/sun.lwawt.macosx.CDropTargetContextPeer.processEnterMessage(CDropTargetContextPeer.java:105)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-16 19:34
Duplicate of #5378

**Closed by Cattlesquat** 2023-02-16 19:34 UTC
Labels: ABR
