### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11750] opened 2022-11-07 11:22 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | pjeffrey@bigpond.net.au |
| Error Log | [7286 bytes](https://vassalengine.org/files/gh/1920a1b9e266d3db24c770da26f6d06b1abd689f) |

<pre>Opening VASL 6.6.5.... maximum Heap size?

3.6.7

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-09 22:01
Duplicate of #9894

**Closed by BrentEaston** 2023-01-09 22:01 UTC
Labels: ABR
