### ISSUE TITLE
[The Spanish Ulcer 1808-1814] NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "VASSAL.build.module.map.DrawPile.getAttributeValueString(String)" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11838] opened 2022-12-23 22:54 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [247314 bytes](https://vassalengine.org/files/gh/b6b110dce00b3a2b847cdd224d66b0db26929ec1) |

<pre>

The Spanish Ulcer 1808-1814 vv12.0     2-players 3.6.9

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "VASSAL.build.module.map.DrawPile.getAttributeValueString(String)" is null
 at VASSAL.build.module.GameRefresher.execute(GameRefresher.java:478)
 at VASSAL.build.module.PredefinedSetup.refresh(PredefinedSetup.java:309)
 at VASSAL.configure.RefreshPredefinedSetupsDialog.refreshPredefinedSetups(RefreshPredefinedSetupsDialog.java:242)
 at VASSAL.configure.RefreshPredefinedSetupsDialog.lambda$initComponents$0(RefreshPredefinedSetupsDialog.java:82)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:11
Duplicate of #11823

**Closed by BrentEaston** 2023-01-07 23:11 UTC
Labels: ABR
