### ISSUE TITLE
[War in the Pacific (SPI, 1977)] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11842] opened 2022-12-28 17:06 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [136847 bytes](https://vassalengine.org/files/gh/e3b07a0f34d66cb6ed842b36a06c850c30374e4f) |

<pre>

War in the Pacific (SPI, 1977) v1.38 3.6.9

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:16
Duplicate of #11299

**Closed by BrentEaston** 2023-01-07 23:16 UTC
Labels: ABR
