### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11711] opened 2022-10-03 14:04 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [31666 bytes](https://vassalengine.org/files/gh/63a1796a2de5ee4267fdf5459845b86cf35b8e37) |

<pre>

3.6.7

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:24
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:24 UTC
Labels: ABR
