### ISSUE TITLE
ExecutionException: java.lang.IllegalStateException: bad type: 91

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11436] opened 2022-05-12 01:40 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [140389 bytes](https://vassalengine.org/files/gh/443783446635f0ab5c29760b1bd8d901a5cf1453) |

<pre>I was opening the module Combat Commander:Europe v2.4. The loading bar made it to "Map12.png" when it crashed

3.6.6

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: bad type: 91
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-09 21:12
Duplicate of #11413

**Closed by Cattlesquat** 2023-02-09 21:12 UTC
Labels: ABR
