### ISSUE TITLE
ExecutionException: java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11717] opened 2022-10-08 11:11 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [466724 bytes](https://vassalengine.org/files/gh/d2e620831228547a865774833ab87027a0d4358e) |

<pre>

3.6.7

java.util.concurrent.ExecutionException: java.util.zip.ZipException: zip END header not found
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-09 21:13
Duplicate of #11683

**Closed by Cattlesquat** 2023-02-09 21:13 UTC
Labels: ABR
