### ISSUE TITLE
[Secret Hitler] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11836] opened 2022-12-23 03:57 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [17338 bytes](https://vassalengine.org/files/gh/5d0e82c8c0c5c319486d76c9ded42ac6d44dd480) |

<pre>

Secret Hitler v0.4 3.6.9

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 03:47
Duplicate of #5813

**Closed by BrentEaston** 2023-01-07 03:47 UTC
Labels: ABR
