### ISSUE TITLE
[Terraforming Mars] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\CorpExpansion.jpg:2,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11532] opened 2022-06-24 12:49 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | meads2052@gmail.com |
| Error Log | [14874 bytes](https://vassalengine.org/files/gh/0c72ce991ec10e998569d5d3ed7dee05f679067d) |

<pre>This bug happens when opening the Corporations and expansions window (the background in the window appears mostly blank). It also happens when opening the help window, and the black player board.

Module - Terraforming Mars C2115 (on Vassal site)
Vassal 3.6.7

Terraforming Mars vC2.1.15 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\CorpExpansion.jpg:2,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by jonathanrwatts** [comment] 2022-06-30 06:05
I just tried opening all 3 of those windows and had no issues.  I suspect either corrupted files or a bad tile cache.  Unless this could be caused by not enough heap memory?

**Comment by jonathanrwatts** [comment] 2022-07-02 22:37
User responded that clearing the tile cache fixed the problem.  I don't believe I have the ability to close this issue, but it's ready to be closed.

**Closed** 2022-09-28 04:13 UTC
Labels: ABR
