### ISSUE TITLE
[Legendary: A Marvel Deck Building Game] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13013] opened 2023-12-25 16:31 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [60551 bytes](https://vassalengine.org/files/gh/7a65acb73a89c937156d88e4db7d719010e1f537) |

<pre>

Legendary: A Marvel Deck Building Game v4.1 3.7.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2024-01-15 21:34
Duplicate of #5813

**Closed by BrentEaston** 2024-01-15 21:34 UTC
Labels: ABR
