### ISSUE TITLE
[VSQL] NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12534] opened 2023-08-06 20:24 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | scott@squadleaderacademy.org |
| Error Log | [74702 bytes](https://vassalengine.org/files/gh/b769d797c79aaebb2712ef23c0a9712c7b5dfefa) |

<pre>UPDATE:
Refresh counters from cod extension 9.2 to 9.3
Refresh erroneiously replaces US leaders with German leaders.
Click on US stack in graveyard throws the error.

VSQL v4.3.5 3.6.19

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:264)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:246)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-08-06 23:23
Duplicate of #12494

**Closed by BrentEaston** 2023-08-06 23:23 UTC
Labels: ABR
