### ISSUE TITLE
[TITE1A] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13054] opened 2024-01-11 01:36 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [394019 bytes](https://vassalengine.org/files/gh/16a4eb0d935e60adeef0648b9a8feca4155166b5) |

<pre>

TITE1A v1.0.0.0 3.7.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2024-01-15 10:19
Duplicate of #5813

**Closed by BrentEaston** 2024-01-15 10:19 UTC
Labels: ABR
