### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11734] opened 2022-10-19 15:19 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | jp.harrison@hotmail.co.uk |
| Error Log | [57105 bytes](https://vassalengine.org/files/gh/c4a5c8236889c73d73fd6587fa463bd9485defab) |

<pre>I was attempting to open FoF_All_Volumes_v3.1.20 for the 1st time. It starts doing it, but stops when it reaches 12% 

3.6.7

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:24
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:24 UTC
Labels: ABR
