### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13327] opened 2024-05-11 16:59 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | pongpanotcshop@gmail.com |
| Error Log | [4171 bytes](https://vassalengine.org/files/gh/04ba862e14675bd2c2feaa1de8e5ae7935baafa8) |

<pre>

3.7.12

java.lang.ExceptionInInitializerError: null
 at VASSAL.launch.ModuleManager.launch(ModuleManager.java:384)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 08:20
Duplicate of #13327

**Closed by BrentEaston** 2024-07-16 08:20 UTC
Labels: ABR
