### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12803] opened 2023-10-12 12:56 UTC
| ABR | |
|-----|-----|
| Version | 3.7.2 |
| Reporter |  |
| Error Log | [10453 bytes](https://vassalengine.org/files/gh/b44771f93e0c3e3428f60a8831a1939d41e9ad92) |

<pre>

3.7.2

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2023-10-18 23:44
Duplicate of #12346

**Closed by BrentEaston** 2023-10-18 23:44 UTC
Labels: ABR
