### ISSUE TITLE
[HeroQuest] IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11592] opened 2022-07-17 16:58 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [7814 bytes](https://vassalengine.org/files/gh/aa648270567e4168c6d4894aefbb68a05b0ccabc) |

<pre>

HeroQuest v0.9 3.6.7

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
 at java.base/java.util.Objects.checkIndex(Objects.java:359)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 05:42
Duplicate of #11520

**Closed by BrentEaston** 2023-01-08 05:42 UTC
Labels: ABR
