### ISSUE TITLE
[Napoleon at Waterloo] InvalidPathException: Illegal char <:> at index 13: odds_marker_2:1.png

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13448] opened 2024-07-05 17:40 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [7333 bytes](https://vassalengine.org/files/gh/c02a2712c01da2c4d496cc02e3fcf2a009ad3a9c) |

<pre>

Napoleon at Waterloo v1.1 3.7.12

java.nio.file.InvalidPathException: Illegal char <:> at index 13: odds_marker_2:1.png
 at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
 at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
 at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
 at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:03
Duplicate of #13313

**Closed by BrentEaston** 2024-07-15 23:03 UTC
Labels: ABR
