### ISSUE TITLE
[Mysterium] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getView()" because "this.map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12031] opened 2023-02-22 17:01 UTC
| ABR | |
|-----|-----|
| Version | 3.6.12 |
| Reporter |  |
| Error Log | [761486 bytes](https://vassalengine.org/files/gh/d75f301a43afbc15496ab73a16a2d219d9d6a234) |

<pre>Copying a folder containing 3 mouse-over stack viewers from one window to a different window in vassal 3.6.12 this time

Mysterium v0.6.1 3.6.12

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getView()" because "this.map" is null
 at VASSAL.build.module.map.CounterDetailViewer.addTo(CounterDetailViewer.java:241)
 at VASSAL.build.Builder.build(Builder.java:82)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
 at VASSAL.configure.ConfigureTree$5.actionPerformed(ConfigureTree.java:680)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-22 19:29
duplicate of already fixed

**Closed by Cattlesquat** 2023-02-22 19:29 UTC
Labels: ABR
