### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11407] opened 2022-04-28 07:25 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [111069 bytes](https://vassalengine.org/files/gh/cc081c195e1127eef86c38019ea20f229c34da4f) |

<pre>

3.6.6

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-09 22:01
Duplicate of #9894

**Closed by BrentEaston** 2023-01-09 22:01 UTC
Labels: ABR
