### ISSUE TITLE
[A House Divided] NullPointerException: Cannot read field "parent" because "comp" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13412] opened 2024-06-22 17:37 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [114315 bytes](https://vassalengine.org/files/gh/49d17e297db16dd156fdfae478ba0daac1d4f11d) |

<pre>Trying to add a Chart Window Menu and put a Scrollable List under it

A House Divided v1.0.9 3.7.12

java.lang.NullPointerException: Cannot read field "parent" because "comp" is null
 at java.desktop/java.awt.Container.remove(Container.java:1290)
 at VASSAL.build.widget.MapWidget.remove(MapWidget.java:104)
 at VASSAL.configure.ConfigureTree.remove(ConfigureTree.java:1376)
 at VASSAL.configure.ConfigureTree.delete(ConfigureTree.java:1368)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:23
Duplicate of #12290

**Closed by BrentEaston** 2024-07-15 23:23 UTC
Labels: ABR
