### ISSUE TITLE
[Warhammer Underworlds Mod] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10278] opened 2021-08-02 09:22 UTC
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | nieto_ja91@hotmail.com |
| Error Log | [282357 bytes](http://www.vassalengine.org/files/gh/89bdde692c4eedcb7c4e6c4314897c4aef644254) |

<pre>

Warhammer Underworlds Mod v4.0 BETA ESPAÑOL 3.5.8

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by Cattlesquat** [comment] 2021-08-02 15:08
Dupe of #5183

**Closed** 2021-08-02 15:08 UTC
Labels: ABR
