### ISSUE TITLE
Refresh Counters resets Dynamic Property if current value is null

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12347] opened 2023-06-05 09:31 UTC
Refresh Counters resets Dynamic Property to its initial value, if its current value is null

May be a limitation of Refresh Counters.

Observed in current C&CNap dev module in a DP called moveRule. Originally the "No Effect" status was signified by a null value in the DP. Once set to this value, a Refresh Counters would reset the value to "stop", which is the initialisation value for that DP.

**Comment by BrentEaston** [comment] 2023-06-24 11:02
Currently, Refresh Counters will always reset a DP to it's default value on refresh, regardless of the value. 

This is probably not the expected behaviour. Markers are reset to the new default value, that make sense, but DP's we probably want to keep the existing value. 

We probably want a new Refresher option 'Reset Dynamic Properties' to default values' defaulting to Off?

**Comment by riverwanderer** [comment] 2023-06-24 11:37
That new option would be helpful, yes.

**Comment by BrentEaston** [comment] 2023-06-25 04:21
Thinking more about this, the option is definitely needed. When refreshing a scenario setup, you probably want to reset the DP's, but if you are refreshing a game in progress, you probably want to keep the existing DP values. It's not possible to infer which is correct, we need to leave it up to the user.

Given that the either behaviour could be deemed 'correct', depending on circumstances, I am going to be cautious and make the default the current behaviour:

Reset Dynamic Property values to their default value? Yes

New build available soon.

**Comment by BrentEaston** [comment] 2023-06-25 04:24
Or, in keeping with the existing Deck option:

Refresh Dynamic Property values with latest default value from module Yes

**Comment by BrentEaston** [comment] 2023-06-25 12:06
@riverwanderer Please try the 12347-RefreshDPOptions when you get a chance.

**Comment by riverwanderer** [comment] 2023-06-25 15:02
The update to Refresh does work but I was surprised that it was the **_checked_** option that preserves the DP setting:

<img width="525" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/820c5af5-33aa-4c17-b4e1-2a4230bc5728">  

Unchecked (the default) changes the pieces to the initial value of the DP.

Maybe I misunderstand what "from the latest default values from the module" means ?

Also, as it stands, it means that the most potentially disruptive action is the default.... at least as I experience it.

**Comment by riverwanderer** [comment] 2023-06-25 15:27
I just noticed that the default is different between the individual and full refresh tools; I guess the second one is the error ?

<img width="592" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/f9addb63-2a9a-419b-8d8a-eb51b7a149c5">

**Comment by BrentEaston** [comment] 2023-06-25 21:54
My thought was that when refreshing pre-defined setups, you probably want to reset everything fully back to what is defined in the module, while an in-game refresh is more likely an on-going game where you don't want to change the DP's current value.

However, it's confusing having the two defaults and the reasoning can never be 100% successful. You may be doing an in-game refresh of an individual pre-defined setup.

I have a minor concern about compatibility - The current behavior is to reset the DP's to current defaults (tick on). But as this is the more disruptive behaviour that cannot be undone, I agree, it is probably best to never have this option pre-ticked in either case.

**Comment by BrentEaston** [comment] 2023-06-25 22:26
New version pushed

**Comment by riverwanderer** [comment] 2023-06-26 10:01
" When refreshing a scenario setup, you probably want to reset the DP's" 

A module of any complexity will likely have more than one DP where the starting value may vary from scenario to scenario. Should a situation arise where you want to reset a DP it is quite likely that you will not want the other(s) to reset. Worse than that, you probably won't even be aware of all the DPs that might get reset... until problems start to emerge.

I am still confused about the options - when I check to Refresh DPs, my scenario DP settings are retained. When the box is clear, the DP settings are reset to their initial values. Is this what you expect to happen?

Also, prior to this change, the Refresh generally retained my scenario DP settings. I only noticed this issue with this recent case where the value had been changed to null. Once I changed it to non-null, the Refresh no longer reset the DP.

**Comment by BrentEaston** [comment] 2023-06-26 11:08
Thanks Mark,

Hmm, not sure what I was fixing, but it wasn't your problem. I think I got confused with the issues from the Replace with Other issue.

I am ripping out everything I've done on this one and starting again.

**Comment by BrentEaston** [comment] 2023-06-26 11:36
Ok, Well that was easier. Turned out to be a one line fix. The state was not being copied over on any trait if the state was empty. DP's (and Markers) where otherwise being handled correctly.

New build [12347-RefreshDPIssue](https://github.com/BrentEaston/vassal/tree/12347-RefreshDPIssue) on the way

**Comment by riverwanderer** [comment] 2023-06-26 12:09
[12347-RefreshDPIssue](https://github.com/BrentEaston/vassal/tree/12347-RefreshDPIssue) tests out ok. I reverted the example DP value back to null, refreshed again and it stayed null. Also, the Refresh still seems to work ok in general.

I have not tested "Refresh Predefined Setups", is it safe to assume that will work if Refresh Counters works, in this case ?

**Comment by BrentEaston** [comment] 2023-06-26 22:56
Yes, the fix is in the underlying function that generates a new piece, used by both refreshers.

Thanks for your help.

**Closed** 2023-06-29 21:29 UTC
Labels: bug, Reproducible
