### ISSUE TITLE
[A Glorious Chance - Playtest v12-1] NPE because DrawPile thinks it doesn't have a Map?!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11392] opened 2022-04-23 05:47 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | ginaworks4u@gmail.com |
| Error Log | [6782 bytes](https://vassalengine.org/files/gh/7a66fc71522cde884d2453cd2137851cacea695f) |

<pre>I was testing a "Return to Deck" command in a card deck. I dealt a series of 7 random cards from a deck of 38 cards, moved them around, and then group-selected all 7 cards with a mouse lasso drag. Then, when I right-clicked and selected "Return to Deck," this Uncaught Exception error occurred.

A Glorious Chance - Playtest v12-1 vApril 2022 3.6.6

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.placeOrMerge(VASSAL.counters.GamePiece, java.awt.Point)" because the return value of "VASSAL.build.module.map.DrawPile.getMap()" is null
 at VASSAL.build.module.map.DrawPile.addToContents(DrawPile.java:1026)
 at VASSAL.build.module.map.DrawPile.addToContents(DrawPile.java:1013)
 at VASSAL.counters.ReturnToDeck.myKeyEvent(ReturnToDeck.java:170)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:492)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-09 21:19
Duplicate of #11360

**Comment by Cattlesquat** [comment] 2023-02-09 21:35
Somehow DrawPiles are thinking they don't have a MAP(!)

**Comment by Cattlesquat** [comment] 2023-02-27 03:08
Fixed by #12048

**Closed by Cattlesquat** 2023-02-27 03:08 UTC
Labels: ABR
