### ISSUE TITLE
[Battle Spirits Saga Simulator] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12387] opened 2023-06-19 21:59 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [8256 bytes](https://vassalengine.org/files/gh/4fd36faaf4fc0053807d2ea0b5a0661c72711855) |

<pre>

Battle Spirits Saga Simulator v1.1.5 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-06-24 10:50
Duplicate of #5813

**Closed by BrentEaston** 2023-06-24 10:50 UTC
Labels: ABR
