### ISSUE TITLE
[HeroQuest - Versione USA] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11888] opened 2023-01-11 13:20 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [84864 bytes](https://vassalengine.org/files/gh/1fdce9c8108262ca26a083a38b430b8b358dd5a5) |

<pre>

HeroQuest - Versione USA vUSA120529 3.6.9

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-15 09:36
Duplicate of #11561

**Closed by BrentEaston** 2023-01-15 09:36 UTC
Labels: ABR
