### ISSUE TITLE
[VASL] IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12980] opened 2023-12-11 00:17 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [207707 bytes](https://vassalengine.org/files/gh/d7a9e507cc6dcc3bbd5b05460eee190c0f856843) |

<pre>

VASL v6.6.7 3.7.5

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
 at java.base/java.util.Objects.checkIndex(Objects.java:372)
</pre>

**Comment by BrentEaston** [comment] 2023-12-11 07:56
Duplicate of #12981

**Closed by BrentEaston** 2023-12-11 07:56 UTC
Labels: ABR
