### ISSUE TITLE
[Twilight Struggle] NullPointerException: Cannot invoke "javax.swing.KeyStroke.equals(Object)" because the return value of "VASSAL.counters.KeyCommand.getKeyStroke()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12451] opened 2023-07-07 12:47 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [20615 bytes](https://vassalengine.org/files/gh/e27abfe7cb382cb5cbc887455c59256a196bb1b6) |

<pre>

Twilight Struggle v3.04a 3.6.19

java.lang.NullPointerException: Cannot invoke "javax.swing.KeyStroke.equals(Object)" because the return value of "VASSAL.counters.KeyCommand.getKeyStroke()" is null
 at ca.mkiefte.Ops.getKeyCommands(Ops.java:176)
 at VASSAL.counters.Decorator.getProperty(Decorator.java:161)
 at ca.mkiefte.Ops.getProperty(Ops.java:144)
 at VASSAL.counters.Decorator.getKeyCommands(Decorator.java:452)
</pre>

**Comment by BrentEaston** [comment] 2023-07-08 23:13
Duplicate of #12281

**Closed by BrentEaston** 2023-07-08 23:13 UTC
Labels: ABR
