### ISSUE TITLE
[VSQL] NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12648] opened 2023-09-04 16:23 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | sbramley1967@hotmail.com |
| Error Log | [11856 bytes](https://vassalengine.org/files/gh/5d8bc21f643e477f9c6364dd5647cbb0e400306b) |

<pre>Opened graveyard and clicked counters to expand stack.

VSQL v4.3.6 3.6.19

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:264)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:246)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-09-06 23:17
Duplicate of #12494

**Closed by BrentEaston** 2023-09-06 23:17 UTC
Labels: ABR
