### ISSUE TITLE
[Battle Spirits [Online Battlers]] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12615] opened 2023-08-26 10:11 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | Michaelchunngai@gmail.com |
| Error Log | [4614716 bytes](https://vassalengine.org/files/gh/9ee406904c15b23844e30c090b74ab761fd6d445) |

<pre>Sitting in front of my pc , idk 

Battle Spirits [Online Battlers] v1.0 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-09-01 12:22
Duplicate of #5813

**Closed by BrentEaston** 2023-09-01 12:22 UTC
Labels: ABR
