### ISSUE TITLE
[A Few Acres Of Snow] NullPointerException: Cannot invoke "VASSAL.build.module.map.DrawPile.addToContents(VASSAL.counters.GamePiece)" because "pile" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12966] opened 2023-12-06 02:34 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | laviastrangiato@gmail.com |
| Error Log | [9757 bytes](https://vassalengine.org/files/gh/131b6d4ea62bf1417ebbdf380e248292354f9aa6) |

<pre>Attempted to 'return to deck' a fortification card within the neutral cards box.

A Few Acres Of Snow v2.2 3.7.5

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.DrawPile.addToContents(VASSAL.counters.GamePiece)" because "pile" is null
 at VASSAL.counters.ReturnToDeck.myKeyEvent(ReturnToDeck.java:174)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:609)
 at VASSAL.counters.KeyBuffer.keyCommand(KeyBuffer.java:250)
 at VASSAL.counters.KeyCommand.actionPerformed(KeyCommand.java:139)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 00:46
duplicate of #12765

**Closed by BrentEaston** 2023-12-09 00:46 UTC
Labels: ABR
