### ISSUE TITLE
[CG Carrier Battle: Philippine Sea] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12104] opened 2023-03-17 14:13 UTC
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter |  |
| Error Log | [16699 bytes](https://vassalengine.org/files/gh/fdc6c7261c8c66014d4b25eb593687ef6d5327f8) |

<pre>Map Window Button icon. I don't want any icon. In prior versions I just canceled the file selection dialog and it would clear the icon. Now it throws an eeek

CG Carrier Battle: Philippine Sea v 3.6.14

java.lang.NullPointerException: null
 at java.base/java.io.File.<init>(File.java:278)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.filenameFilterCallback(GtkFileDialogPeer.java:107)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.run(Native Method)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.showNativeDialog(GtkFileDialogPeer.java:195)
</pre>

**Comment by BrentEaston** [comment] 2023-04-19 03:44
Duplicate of #12115

**Closed by BrentEaston** 2023-04-19 03:44 UTC
Labels: ABR
