### ISSUE TITLE
[The Other Side] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12818] opened 2023-10-16 00:49 UTC
| ABR | |
|-----|-----|
| Version | 3.7.2 |
| Reporter |  |
| Error Log | [7855 bytes](https://vassalengine.org/files/gh/50652068ccc1c552d88821367af9023e59f703ef) |

<pre>sining in

The Other Side vv.1.3.2 3.7.2

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-10-18 23:37
Duplicate of #5813

**Closed by BrentEaston** 2023-10-18 23:37 UTC
Labels: ABR
