### ISSUE TITLE
IllegalArgumentException: node must be a TreeTableNode managed by this model

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13436] opened 2024-07-01 04:20 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [47738 bytes](https://vassalengine.org/files/gh/911dfef3813797b109789409d99ced1db4c09d4a) |

<pre>

3.7.12

java.lang.IllegalArgumentException: node must be a TreeTableNode managed by this model
 at org.jdesktop.swingx.treetable.DefaultTreeTableModel.isLeaf(DefaultTreeTableModel.java:312)
 at org.jdesktop.swingx.JXTreeTable$TreeTableHackerExt5.getEventForTreeRenderer(JXTreeTable.java:716)
 at org.jdesktop.swingx.JXTreeTable$TreeTableHackerExt4.hitHandleDetectionFromProcessMouse(JXTreeTable.java:622)
 at org.jdesktop.swingx.JXTreeTable.processMouseEvent(JXTreeTable.java:450)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:20
Duplicate of #9867

**Closed by BrentEaston** 2024-07-15 23:20 UTC
Labels: ABR
