### ISSUE TITLE
[Commands & Colors: Napoleonics V5] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13337] opened 2024-05-19 22:06 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | markben61@gmail.com |
| Error Log | [113545 bytes](https://vassalengine.org/files/gh/01e6a39f6fe5e350f8ef0792f12ac2052212ba18) |

<pre>Examining a log file in the editor.

Commands & Colors: Napoleonics V5 v5.0.0a1004 3.7.12

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2577)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:274)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:248)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:25
Duplicate of #12033

**Closed by BrentEaston** 2024-07-16 06:25 UTC
Labels: ABR
