### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11433] opened 2022-05-10 16:39 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | nick@henfrey.net |
| Error Log | [7290 bytes](https://vassalengine.org/files/gh/e29bbc2b0c64537aee5583e116a2c015b1b128cb) |

<pre>vassal 3.3.6 giving ambiguous heap size warnings and crashing repeatedly

3.6.6

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by uckelman** [comment] 2022-05-20 20:53
Emailed user for details.

**Comment by riverwanderer** [comment] 2022-09-28 04:53
Duplicate of https://github.com/vassalengine/vassal/issues/11408.

**Closed by riverwanderer** 2022-09-28 04:53 UTC
Labels: ABR
