### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11522] opened 2022-06-20 12:53 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [6832 bytes](https://vassalengine.org/files/gh/4c23e700b7d1ebacfdec1b0ba6b812f3b1ee484a) |

<pre>

3.6.7

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by riverwanderer** [comment] 2022-09-28 04:53
Duplicate of https://github.com/vassalengine/vassal/issues/11408.

**Closed by riverwanderer** 2022-09-28 04:53 UTC
Labels: ABR
