### ISSUE TITLE
[Star Realms] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11399] opened 2022-04-27 02:58 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [32559 bytes](https://vassalengine.org/files/gh/e95929449c413f673ac6d6fb9fbd1062406013c9) |

<pre>starting an online star realms game

Star Realms v1.1.0 3.6.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:37
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:37 UTC
Labels: ABR
