### ISSUE TITLE
[Vietnam 1965-1975 GMT] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11839] opened 2022-12-26 00:27 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [70958 bytes](https://vassalengine.org/files/gh/c80517bbb84585cb6e00dff5a985a0faed1cac06) |

<pre>

Vietnam 1965-1975 GMT vv.2.06 3.6.9

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 03:46
Duplicate of #5813

**Closed by BrentEaston** 2023-01-07 03:46 UTC
Labels: ABR
