### ISSUE TITLE
ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13464] opened 2024-07-13 04:12 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | CarrierPSU@msn.com |
| Error Log | [29836 bytes](https://vassalengine.org/files/gh/4ba2e4a7475acb9b111b2f292b640fe002f9c0fc) |

<pre>Tried opening vasl-6.6.8.vmod by double-clicking on the file in Windows Explorer

3.7.12

java.util.concurrent.ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 22:58
Duplicate of #12292

**Closed by BrentEaston** 2024-07-15 22:58 UTC
Labels: ABR
