### ISSUE TITLE
[VSQL] NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12809] opened 2023-10-12 22:30 UTC
| ABR | |
|-----|-----|
| Version | 3.7.2 |
| Reporter | btrap2930@gmail.com |
| Error Log | [91875 bytes](https://vassalengine.org/files/gh/9a4a1f470f1a92c98a7ff28573c98f1b8156ce37) |

<pre>open the graveyard and try to click on a unit

VSQL v4.3.7 3.7.2

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:265)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:247)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-10-18 23:43
Duplicate of #12494

**Closed by BrentEaston** 2023-10-18 23:43 UTC
Labels: ABR
