### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13308] opened 2024-04-30 03:42 UTC
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter | 514805329@qq.com |
| Error Log | [5111 bytes](https://vassalengine.org/files/gh/0b2481b74cd43134d11057dfa6d826823380641e) |

<pre>

3.7.10

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:23
Duplicate of #12346

**Closed by BrentEaston** 2024-07-16 06:23 UTC
Labels: ABR
