### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12711] opened 2023-09-16 01:59 UTC
| ABR | |
|-----|-----|
| Version | 3.7.0 |
| Reporter | ferencvarimark@gmail.com |
| Error Log | [7141 bytes](https://vassalengine.org/files/gh/8cb0b2ab27026e850fdedb024cb5798c52e10be8) |

<pre>just loaded Twilight Struggle 3.1.2 modul for the first time

Twilight Struggle 3.1 v3.1.2 3.7.0

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2023-09-18 04:01
Duplicate of #11874

**Closed by BrentEaston** 2023-09-18 04:01 UTC
Labels: ABR
