### ISSUE TITLE
[Next War: Korea 2nd Edition] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11472] opened 2022-05-28 00:28 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [18173 bytes](https://vassalengine.org/files/gh/5c7ed6583e286e446edfecb4ee20582b336aa930) |

<pre>

Next War: Korea 2nd Edition v1.4 3.6.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:38
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:38 UTC
Labels: ABR
