### ISSUE TITLE
[Eldritch Horror] NoSuchMethodError: 'void foobarius.HoldableDecorator.setOldProperties()'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11338] opened 2022-04-03 20:45 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | bob@sheilaoop.com |
| Error Log | [8000 bytes](https://vassalengine.org/files/gh/a6dbbed5e39342ab9dc0f6c0fcb0db9f056db888) |

<pre>Moving a card with tokens on it in the Ancient One window. The card moved but not the tokens

Eldritch Horror v1.9.1 3.6.6

java.lang.NoSuchMethodError: 'void foobarius.HoldableDecorator.setOldProperties()'
 at foobarius.HoldableDecorator.followHolder(HoldableDecorator.java:239)
 at foobarius.HolderDecorator.myKeyEvent(HolderDecorator.java:135)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:492)
 at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:165)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 03:16
Duplicate of #11268

**Closed by BrentEaston** 2023-01-08 03:16 UTC
Labels: ABR
