### ISSUE TITLE
[VASL] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12487] opened 2023-07-23 15:24 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | stuartdm@btinternet.com |
| Error Log | [136809 bytes](https://vassalengine.org/files/gh/7a28dbcced7d56d8cb742768d42bc242a034292d) |

<pre>In VASL 6.6.6.  Applying Terrain SSR to boards 34, 35, 36, 37.  Using the 'PTO Transformarions' option.  Boards 35 and 37 disappear after the error.

It has happen each time I tried it.

VASL v6.6.6 3.6.19

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment] 2023-07-25 05:49
Duplicate of #12453

**Closed by BrentEaston** 2023-07-25 05:49 UTC
Labels: ABR
