### ISSUE TITLE
[WS - Fall Blau] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10332] opened 2021-08-20 18:25 UTC
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [2505 bytes](http://www.vassalengine.org/files/gh/a210e94a48cea7325e5590bd3cd0d621dff5ca1d) |

<pre>

WS - Fall Blau v007.3 3.5.8

java.lang.NullPointerException: null
 at java.base/java.io.File.<init>(File.java:278)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.filenameFilterCallback(GtkFileDialogPeer.java:107)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.run(Native Method)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.showNativeDialog(GtkFileDialogPeer.java:195)
</pre>

**Comment by BrentEaston** [comment] 2021-08-21 02:32
Duplicate of #10330

**Closed by BrentEaston** 2021-08-21 02:32 UTC
Labels: ABR
