### ISSUE TITLE
ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13219] opened 2024-03-19 10:44 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter |  |
| Error Log | [72998 bytes](https://vassalengine.org/files/gh/f6771ac202fa1bdbc1fd19715f9a9e55905da7f5) |

<pre>

3.7.9

java.util.concurrent.ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-04-13 05:41
Duplicate of #12292

**Closed by BrentEaston** 2024-04-13 05:41 UTC
Labels: ABR
