### ISSUE TITLE
[Civilization: A new Dawn] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12956] opened 2023-12-02 08:41 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [192653 bytes](https://vassalengine.org/files/gh/e60d66f2476a8495790a7ccebc812f4a4582fd1b) |

<pre>Creating nickname and password for Civilization A New Dawn looking for an online game

Civilization: A new Dawn v1.0 3.7.5

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2024-01-24 08:11
Duplicate of #5813

**Closed** 2024-07-24 00:02 UTC
Labels: Out of date VASSAL version
