### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11736] opened 2022-10-24 05:53 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | allan.manser@hotmail.com |
| Error Log | [2668 bytes](https://vassalengine.org/files/gh/132fddbe28334b034e2bdc2b896c25f7d65bb9fa) |

<pre>Opening the latest version (3.6.7) on to  my laptop. Previously the download had worked fine

3.6.7

java.lang.reflect.InvocationTargetException: null
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
 at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
 at VASSAL.launch.StartUp.initUIProperties(StartUp.java:107)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 03:01
Duplicate of #11240

**Closed by BrentEaston** 2023-01-08 03:01 UTC
Labels: ABR
