### ISSUE TITLE
[War of Religion] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11566] opened 2022-07-05 20:02 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [5541 bytes](https://vassalengine.org/files/gh/6bd38000e9481895ee73dcbef6496bd3c8571ab3) |

<pre>

War of Religion v0.0.5 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null
 at VASSAL.build.module.map.SetupStack.setup(SetupStack.java:269)
 at VASSAL.build.module.GameState.setup(GameState.java:533)
 at VASSAL.build.module.GameState$8.actionPerformed(GameState.java:247)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-17 20:58
Duplicate of #12008

**Closed by Cattlesquat** 2023-02-17 20:58 UTC
Labels: ABR
