### ISSUE TITLE
[Combat Commander: Europe] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12921] opened 2023-11-21 11:34 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | danielshuffman@gmail.com |
| Error Log | [13743 bytes](https://vassalengine.org/files/gh/8795a832961c5c17b2639d840cc9993e84b2c34e) |

<pre>Draging German card to Die Roll

Combat Commander: Europe v2.4 3.7.5

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2576)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:273)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:247)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 02:14
Duplicate of #12033

**Closed by BrentEaston** 2023-12-09 02:14 UTC
Labels: ABR
