### ISSUE TITLE
[Battlestar Galactica FFG] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11731] opened 2022-10-17 14:36 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | Fyufk@hotmail.fr |
| Error Log | [89067 bytes](https://vassalengine.org/files/gh/dbe6af54d820a7b108039ba7dbc27e0abc640d0e) |

<pre>

Battlestar Galactica FFG v4.7.01 3.6.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 04:19
Duplicate of #11561

**Closed by BrentEaston** 2023-01-07 04:19 UTC
Labels: ABR
