### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13065] opened 2024-01-14 19:02 UTC
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter |  |
| Error Log | [16016 bytes](https://vassalengine.org/files/gh/d63e1e5c094072a31d51053f2d53b20e17bb9a51) |

<pre>

Twilight Struggle 3.1 v3.1.2 3.7.7

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2024-01-15 10:12
Duplicate of #11874

**Closed by BrentEaston** 2024-01-15 10:12 UTC
Labels: ABR
