### ISSUE TITLE
[Arena Rex] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11481] opened 2022-06-02 00:40 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | shotglass@gmail.com |
| Error Log | [41335 bytes](https://vassalengine.org/files/gh/f725bd31d334f14aa9fa03ac483faa7029fd24cd) |

<pre>new install

Arena Rex v0.68 3.6.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:38
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:38 UTC
Labels: ABR
