### ISSUE TITLE
ExecutionException: java.lang.IllegalStateException: bad type: 91

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11921] opened 2023-01-23 08:07 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [12632 bytes](https://vassalengine.org/files/gh/162c884fcfdc310130f91b4ca32b471e7baa2670) |

<pre>

3.6.10

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: bad type: 91
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-09 21:11
Duplicate of #11413

**Closed by Cattlesquat** 2023-02-09 21:11 UTC
Labels: ABR
