### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11856] opened 2023-01-06 16:58 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter | ppenza@aol.com |
| Error Log | [24013 bytes](https://vassalengine.org/files/gh/705c6ce258b48e834d3a99e46394768678e8236d) |

<pre>I am trying to opem module 2.7 of  A TIME FOR TRUMPETS

3.6.9

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:23
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:23 UTC
Labels: ABR
