### ISSUE TITLE
[SW Epic Duels] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12398] opened 2023-06-25 00:14 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | leonardofvn@gmail.com |
| Error Log | [10421 bytes](https://vassalengine.org/files/gh/436cbbfb6cb9266bb822af6f8b7dcb69b438f104) |

<pre>

SW Epic Duels v3.2 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-06-26 01:17
Duplicate of #5813

**Closed by BrentEaston** 2023-06-26 01:17 UTC
Labels: ABR
