### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13232] opened 2024-03-27 04:38 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter |  |
| Error Log | [24552 bytes](https://vassalengine.org/files/gh/ec8e86b4a4a02117fb215a1a85226361d6dd8fb7) |

<pre>

3.7.9

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:22
Duplicate of #12346

**Closed by BrentEaston** 2024-07-16 06:22 UTC
Labels: ABR
