### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11485] opened 2022-06-03 09:04 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [1974219 bytes](https://vassalengine.org/files/gh/825c156cc5326d44632d242ad6818c26e4818504) |

<pre>

3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/BSOB Classic.png:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by riverwanderer** [comment] 2022-09-28 04:53
Duplicate of https://github.com/vassalengine/vassal/issues/11408.

**Closed by riverwanderer** 2022-09-28 04:53 UTC
Labels: ABR
