### ISSUE TITLE
ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12452] opened 2023-07-07 23:58 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [32622 bytes](https://vassalengine.org/files/gh/b9bacaa16dcad0ab860508f59ff5c975f1435f41) |

<pre>

3.6.19

java.util.concurrent.ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:519)
</pre>

**Comment by BrentEaston** [comment] 2023-07-08 23:15
Duplicate of #12292

**Closed by BrentEaston** 2023-07-08 23:15 UTC
Labels: ABR
