### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11767] opened 2022-11-17 03:57 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [30893 bytes](https://vassalengine.org/files/gh/d04895e8e3145012dff510bf12f32a9003574e60) |

<pre>Opening D-Day at Omaha Beac v4.1 vmod

3.6.7

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:24
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:24 UTC
Labels: ABR
