### ISSUE TITLE
[Air Superiority] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/air_sup_teams_screen_A.png:0,15@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13498] opened 2024-07-22 16:13 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | clayjensen@me.com |
| Error Log | [14346 bytes](https://vassalengine.org/files/gh/6b2748b98e4c74f9cd7729db011e062b8c11cf17) |

<pre>Hello! This error occurred for me as I was editing a rectangular grid for a map board. The error message appeared as I was scrolling down across the map image and was triggered at the exact moment I scrolled past the bottom of the map image itself (into the white background). I was working on my own module at the time and am on this version/setup:

VASSAL 3.7.12

MacBook Pro (16-inch, 2021)
Memory 32 GB
macOS Sonoma 14.5

I hope this helps!   :)

Clay

Air Superiority v2.54 3.7.12

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/air_sup_teams_screen_A.png:0,15@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:326)
</pre>

**Comment by BrentEaston** [comment] 2024-07-22 22:41
Duplicate of #13100

**Closed by BrentEaston** 2024-07-22 22:41 UTC
Labels: ABR
