### ISSUE TITLE
[Holland '44] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12613] opened 2023-08-25 14:55 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | yes0001 |
| Error Log | [9909 bytes](https://vassalengine.org/files/gh/53012b02cc62c01de9622e441cfaafc8e27969fb) |

<pre>helo012g2e

Holland '44 v0.92 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-09-01 12:21
Duplicate of #5813

**Closed by BrentEaston** 2023-09-01 12:21 UTC
Labels: ABR
