### ISSUE TITLE
[Jeu de Bataille de la Terre du Milieu] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12785] opened 2023-10-04 19:37 UTC
| ABR | |
|-----|-----|
| Version | 3.7.1 |
| Reporter | macfly0024@gmail.com |
| Error Log | [320403 bytes](https://vassalengine.org/files/gh/b0da07be2e31cd7808e8753ce24cdc0ba30e04ed) |

<pre>

Jeu de Bataille de la Terre du Milieu v1.6 3.7.1

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-10-04 21:54
Duplicate of #5813

**Closed by BrentEaston** 2023-10-04 21:54 UTC
Labels: ABR
