### ISSUE TITLE
[Commands & Colors Ancients] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11593] opened 2022-07-17 18:33 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | markben61@gmail.com |
| Error Log | [475629 bytes](https://vassalengine.org/files/gh/e1750055737abb7927f4aef0c713f90e8fa96712) |

<pre>putting a button image on an action button				

Commands & Colors Ancients v4.2.0a65 3.6.7

java.lang.StackOverflowError: null
 at java.base/java.security.AccessController.getContext(AccessController.java:1003)
 at java.desktop/java.awt.AWTEvent.<init>(AWTEvent.java:120)
 at java.desktop/java.awt.event.InvocationEvent.<init>(InvocationEvent.java:291)
 at java.desktop/java.awt.event.InvocationEvent.<init>(InvocationEvent.java:177)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 20:23
Duplicate of #11591

**Closed** 2023-02-10 20:25 UTC
Labels: ABR
