### ISSUE TITLE
[All Bridges Burning] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11903] opened 2023-01-17 19:06 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [243226 bytes](https://vassalengine.org/files/gh/4e26c4c410b7dd0d26dd71b32fb6383a9b7c0a78) |

<pre>

All Bridges Burning v1.2 3.6.10

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-25 11:03
Duplicate of #11561

**Closed by BrentEaston** 2023-01-25 11:03 UTC
Labels: ABR
