### ISSUE TITLE
[Commands & Colors: Napoleonics V5] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13226] opened 2024-03-25 19:30 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | markben61@gmail.com |
| Error Log | [2629637 bytes](https://vassalengine.org/files/gh/2ec422f0b6e15cdaf5913e8de10b07ca7b2179e0) |

<pre>I clicked on second "Paper-Strength" counter from the bottom in a stack of four, whilst investigating a log file to understand why only a double-click on the bottom counter seems to expand the stack.

Commands & Colors: Napoleonics V5 v5.0.0a129 3.7.9

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2577)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:277)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:251)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:25
Duplicate of #12033

**Closed by BrentEaston** 2024-07-16 06:25 UTC
Labels: ABR
