### ISSUE TITLE
ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12616] opened 2023-08-26 18:13 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | anderson.jimn@gmail.com |
| Error Log | [7729 bytes](https://vassalengine.org/files/gh/9808539faf9ae9af7634aa6d9f4874a6ebb7f8ea) |

<pre>Downloaded module: La Bataille de Ligney II.  Version 1.23.  Previous version 1.22 worked fine and I had a saved game.  Attempting to load new version and it cannot load past the map images.  Now version 1.22 doesn't load.  I tried deleting 1.22 and redownloaded 1.23.  Still not loading.  In preferences I increased the size allowed from 1024 to 2058.  Still no joy.

3.6.19

java.util.concurrent.ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:519)
</pre>

**Comment by BrentEaston** [comment] 2023-09-01 12:24
Duplicate of #12292

**Closed by BrentEaston** 2023-09-01 12:24 UTC
Labels: ABR
