### ISSUE TITLE
[Unhappy King Charles] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11561] opened 2022-06-30 22:18 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [70527 bytes](https://vassalengine.org/files/gh/7da44dd7e584d6a2f031b7b4956aa754de7045a7) |

<pre>

Unhappy King Charles v4.0.2 3.6.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 20:34
Duplicate of #5813

**Closed by Cattlesquat** 2023-02-10 20:34 UTC
Labels: ABR
