### ISSUE TITLE
A simple VP city counting tool.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#4699] opened 2021-06-28 16:43 UTC
| Bugzilla |  |
|----------|----------|
| ID | BZ2107 |
| Reported | 2008-01-07 07:05:00 +0100 |
| Modified | 2020-06-22 00:12:37 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | unspecified |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | low |
| Severity | enhancement |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2010-08-25 14:35:37 +0200
<pre>---- Reported by  2008-01-07 07:05 ----

Details here:
http://vassalengine.org/forums/viewtopic.php?t=153

--- Bug imported by uckelman@nomic.net 2010-08-25 14:36 MST  ---

This bug was previously known as _bug_ 1865690 at http://www.vassalengine.org/trackershow_bug.cgi?id=1865690

Unknown Component 
   Using default product and component set in Parameters 
The original reporter of this bug does not have
   an account here. Reassigning to the person who moved
   it here: uckelman@nomic.net.
   Previous reporter is unknown.
The original assignee of this bug does not have
   an account here. Reassigning to the default assignee
   for the component, uckelman@nomic.net.
   Previous assignee was Brent Easton.
Missing Resolution. Setting status to NEW
Unknown resolution "".
   Setting resolution to MOVED</pre>

**Comment by BrentEaston** [comment] 2021-07-04 01:00
Duplicate of #4474

**Closed by BrentEaston** 2021-07-04 01:00 UTC
