### ISSUE TITLE
[Ticket to Ride: Europe] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11741] opened 2022-10-29 14:27 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [26605 bytes](https://vassalengine.org/files/gh/c0894b4ad9009de62750ee7fdb7b9779ec0e29d5) |

<pre>

Ticket to Ride: Europe v0.51 3.6.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 03:47
Duplicate of #5813

**Closed by BrentEaston** 2023-01-07 03:48 UTC
Labels: ABR
