### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12336] opened 2023-05-30 15:43 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [2948 bytes](https://vassalengine.org/files/gh/ab2f8aaf15a5657e4d48e0efd780a2bb29eb0069) |

<pre>

3.6.19

java.lang.ExceptionInInitializerError: null
 at VASSAL.launch.ModuleManager.launch(ModuleManager.java:384)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 03:33
Duplicate of #12849

**Closed by BrentEaston** 2023-12-09 03:33 UTC
Labels: ABR
