### ISSUE TITLE
Pre-defined Scenarios in Extension folders can be dragged into Module folders and become non-editable

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#11337] opened 2022-04-03 14:13 UTC
Vassal v3.6.6 (Editor)

I have been using drag & drop to re-order scenarios in an Extension (specifically Flying Colors). I have noticed that items seem to disappear.

In the most recent example of a problem, I dragged an item to a new pre-defined scenario folder that I'd just put another item in. The second item "missed" the folder somehow and ended up in the higher level pre-defined folder. However, it was now greyed out as if it was not editable in the extension and indeed could not be moved.  I saved and re-opened the extension for edit, to find that this second item has now disappeared.  Using the old method - context menu command "Move" - has worked reliably when I've tried that.

**Comment by riverwanderer** [comment] 2022-04-04 13:54
Also occurs when editing pieces. Probably a general problem. Happens when a piece is accidentally dragged into a part of the folder structure where an extension element is not allowed.

Workaround: Copy the greyed out element and paste it into the correct location (e.g. Extension pieces folder). Save and re-open the extension for edit. The copied element will be in place correctly and the greyed out element will have disappeared.

**Comment by BrentEaston** [comment] 2023-06-27 04:41
Duplicate of #12403

**Comment by BrentEaston** [comment] 2023-06-27 04:51
@riverwanderer I have reproduced the problems with Drag and Drop when editing Extensions and am addressing them in #12413.

I cannot reproduce the other issue you report where a piece can be dropped in a folder it is not allowed to be in and can no longer be edited. I'd be interested if you can still reproduce this?

Thanks.

**Comment by riverwanderer** [comment] 2023-06-27 09:47
@BrentEaston - yes, just tested now with Flying Colors and its extension. I just dragged two PDS from "Ship of the Line Scenarios" (an extension component) into the above "Fleet Actions" PDS folder (a core module component), it's the last two greyed out ones:
<img width="365" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/b8c56159-a1c0-4ad4-839b-c61930242da7">

I assume that I should not be able to do this. Anyway, I certainly can't drag them back into "Ship of the Line Scenarios".
When I save the modified extension, the 2 affected PDS are removed.

**Comment by BrentEaston** [comment] 2023-06-28 06:52
Aha, thank you. I have reproduced that. It doesn't seem to happen with other component types, just with the Pre-defined Scenarios.

**Comment by BrentEaston** [comment] 2023-06-28 07:18
I am going take this issue over for the Invalid Dnd issue. #12403 will handle the DnD changes not sticking issue.

See Also #12403

**Comment by BrentEaston** [comment] 2023-06-28 23:59
The new build VASSAL-3.7.0-SNAPSHOT-139ce7c-12403-ExtensionCutPaste I made to handle the Drag and Drop issues also seems to fix this issue.

**Closed** 2023-07-01 00:02 UTC
Labels: bug, Reproducible
