### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13236] opened 2024-03-27 14:33 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | chudy.xu@gmail.com |
| Error Log | [2668 bytes](https://vassalengine.org/files/gh/5ded6679fad6f86765ebd70d2c04d9465b4bcfc6) |

<pre>I have no idea how to recreate it, homever it appeared just as i loaded a save file for VASL.

3.7.9

java.lang.reflect.InvocationTargetException: null
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
 at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
 at VASSAL.launch.StartUp.initUIProperties(StartUp.java:107)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:36
Duplicate of #11240

**Closed by BrentEaston** 2024-07-16 06:36 UTC
Labels: ABR
