### ISSUE TITLE
[Battle Spirits [Online Battlers]] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12751] opened 2023-09-27 12:25 UTC
| ABR | |
|-----|-----|
| Version | 3.7.1 |
| Reporter |  |
| Error Log | [16977 bytes](https://vassalengine.org/files/gh/7fb57e549a6b6a5dca876ad6b7638f7dd44934e8) |

<pre>

Battle Spirits [Online Battlers] v1.0 3.7.1

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-10-02 01:51
Duplicate of #5813

**Closed by BrentEaston** 2023-10-02 01:51 UTC
Labels: ABR
