### ISSUE TITLE
[NAPOLEON CONQUEST] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11863] opened 2023-01-07 16:28 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [5732 bytes](https://vassalengine.org/files/gh/5126b7319d7c4e1ba0b0ca22d3d61bcb1ad57fa1) |

<pre>

NAPOLEON CONQUEST v0.0.1 3.6.9

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null
 at VASSAL.counters.Decorator.getOutermost(Decorator.java:525)
 at VASSAL.build.widget.PieceSlot.getLocalizedConfigureName(PieceSlot.java:609)
 at VASSAL.build.Widget$MyCellRenderer.getListCellRendererComponent(Widget.java:183)
 at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1444)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 22:20
Duplicate of #11813

**Closed by BrentEaston** 2023-01-07 22:20 UTC
Labels: ABR
