### ISSUE TITLE
ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11807] opened 2022-12-03 00:55 UTC
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter |  |
| Error Log | [4656 bytes](https://vassalengine.org/files/gh/63dd185f4a3fed8b326f5d62176b403588740a23) |

<pre>open POG module, i can open all other ones but POG

3.6.8

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:24
Duplicate of #11800

**Closed by BrentEaston** 2023-01-07 23:24 UTC
Labels: ABR
