### ISSUE TITLE
ExecutionException: java.io.IOException: Cannot delete file: /Users/edzaccount/Library/Application Support/VASSAL/tiles/29bf64cd88d3e9db205b056eaa55980b4d15e47f

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11694] opened 2022-09-19 20:22 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | edwski@comcast.net |
| Error Log | [16156 bytes](https://vassalengine.org/files/gh/a59b1e59bd20303381289eec8e481a1e3614251a) |

<pre>

3.6.7

java.util.concurrent.ExecutionException: java.io.IOException: Cannot delete file: /Users/edzaccount/Library/Application Support/VASSAL/tiles/29bf64cd88d3e9db205b056eaa55980b4d15e47f
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by riverwanderer** [comment] 2022-09-28 04:57
Duplicate of ##11357.

**Closed by riverwanderer** 2022-09-28 04:57 UTC
Labels: ABR
