### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12383] opened 2023-06-19 05:46 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [68637 bytes](https://vassalengine.org/files/gh/3c2da36c89a53cad128a8465a360a5589d8643ad) |

<pre>

3.6.19

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:519)
</pre>

**Comment by BrentEaston** [comment] 2023-08-01 21:02
Duplicate of #12346

**Closed by BrentEaston** 2023-08-01 21:02 UTC
Labels: ABR
