### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11428] opened 2022-05-07 02:05 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | gratton1hondo@hotmail.com |
| Error Log | [40594 bytes](https://vassalengine.org/files/gh/adce9b06e207e5e3aedbb91bc3195ccf0711f429) |

<pre>I was just downloading 1_34 VMOD for World in Flames.

3.6.6

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:25
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:25 UTC
Labels: ABR
