### ISSUE TITLE
[Pacific War 2] NullPointerException: Cannot invoke "VASSAL.build.module.properties.PropertySource.getProperty(Object)" because "this.source" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11835] opened 2022-12-22 11:43 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [8194 bytes](https://vassalengine.org/files/gh/736b896786c08667463679ae37602bc398ade03c) |

<pre>

Pacific War 2 v2.00.025 3.6.9

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.PropertySource.getProperty(Object)" because "this.source" is null
 at VASSAL.script.ExpressionInterpreter.evaluate(ExpressionInterpreter.java:273)
 at VASSAL.script.expression.BeanShellExpression.evaluate(BeanShellExpression.java:65)
 at VASSAL.script.expression.Expression.tryEvaluate(Expression.java:213)
 at VASSAL.script.expression.Expression.tryEvaluate(Expression.java:138)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 19:46
Duplicate of #11304

**Closed by Cattlesquat** 2023-02-10 19:46 UTC
Labels: ABR
