### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11855] opened 2023-01-06 16:52 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [25604 bytes](https://vassalengine.org/files/gh/ee1fc6328715faa9821a24d228da94fc10142521) |

<pre>I just downloaded module 2.7 of A TIME FOR TRUMPETS

3.6.9

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:23
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:23 UTC
Labels: ABR
