### ISSUE TITLE
ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13279] opened 2024-04-17 13:26 UTC
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter |  |
| Error Log | [199719 bytes](https://vassalengine.org/files/gh/b781681c7422aa653751cb8b37d4882ce3aa524e) |

<pre>just booting

3.7.10

java.util.concurrent.ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 22:57
Duplicate of #12292

**Closed by BrentEaston** 2024-07-15 22:57 UTC
Labels: ABR
