### ISSUE TITLE
[Table Battles] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11889] opened 2023-01-12 01:10 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [42113 bytes](https://vassalengine.org/files/gh/bf1675c6c1ecc5fd2830af760863dfb9993b6e25) |

<pre>

Table Battles v1.0 3.6.10

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-15 09:36
Duplicate of #11561

**Closed by BrentEaston** 2023-01-15 09:36 UTC
Labels: ABR
