### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13031] opened 2024-01-02 08:42 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter | tav1967@gmail.com |
| Error Log | [2674 bytes](https://vassalengine.org/files/gh/1aa9dc3e045a893ab8529cd35de92704158bdb34) |

<pre>So far I have used Vassal with an "official" module of PoG, and everything has been alright.

However since a couple of days ago i couldn,t run the logs other players sent me, nor those i had kept.

I tried uninstalling Vassal, but when i download it again, there are several mistakes, so I can not get all the files.

Therefore just now i don,t have Vassal at all

3.7.6

java.lang.reflect.InvocationTargetException: null
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
 at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
 at VASSAL.launch.StartUp.initUIProperties(StartUp.java:107)
</pre>

**Comment by BrentEaston** [comment] 2024-01-03 22:40
Seems to be corrupted prefs file

**Comment by BrentEaston** [comment] 2024-07-16 06:36
Duplicate of #11240

**Closed by BrentEaston** 2024-07-16 06:36 UTC
Labels: ABR
