### ISSUE TITLE
[A House Divided] NullPointerException: Cannot read field "parent" because "comp" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13413] opened 2024-06-22 17:39 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [119639 bytes](https://vassalengine.org/files/gh/b25fa1a408c1318cc1132be2ddb15f84cfdd9183) |

<pre>Won't let me delete the Chart Window Menu I added. 

A House Divided v1.0.9 3.7.12

java.lang.NullPointerException: Cannot read field "parent" because "comp" is null
 at java.desktop/java.awt.Container.remove(Container.java:1290)
 at VASSAL.build.widget.MapWidget.remove(MapWidget.java:104)
 at VASSAL.configure.ConfigureTree.remove(ConfigureTree.java:1376)
 at VASSAL.configure.ConfigureTree.delete(ConfigureTree.java:1368)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 05:08
Duplicate of #13412

**Closed by BrentEaston** 2024-07-15 05:08 UTC
Labels: ABR
