### ISSUE TITLE
[Fourth Millennium] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Card Back.jpg:0,4@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12662] opened 2023-09-06 19:11 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | darrellkhanning@gmail.com |
| Error Log | [88862 bytes](https://vassalengine.org/files/gh/fe0519d162f4cf8d9f868e42e828ac3d766ad28e) |

<pre>Attempting to redefine an irregular grid, after deleting one of its members.

Fourth Millennium vv1.0 3.6.19

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Card Back.jpg:0,4@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment] 2024-01-25 23:13
Duplicate of #10937

**Closed by BrentEaston** 2024-01-25 23:13 UTC
Labels: ABR
