### ISSUE TITLE
[Hastings 1066] NullPointerException: Cannot invoke "VASSAL.configure.Parameter.encode()" because "param" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12790] opened 2023-10-05 23:51 UTC
| ABR | |
|-----|-----|
| Version | 3.7.1 |
| Reporter | djberg96@gmail.com |
| Error Log | [21669 bytes](https://vassalengine.org/files/gh/d12f40ba0a26c80292eb4240539975c82c5eac5c) |

<pre>I was fiddling around with the Place Marker attribute. I was going to add a dynamic property, but then changed my mind and hit cancel. That's when the error happened.

Hastings 1066 v0.1 3.7.1

java.lang.NullPointerException: Cannot invoke "VASSAL.configure.Parameter.encode()" because "param" is null
 at VASSAL.configure.ParameterListConfigurer.encode(ParameterListConfigurer.java:58)
 at VASSAL.counters.PlaceMarker.myGetType(PlaceMarker.java:178)
 at VASSAL.counters.Decorator.getType(Decorator.java:527)
 at VASSAL.counters.PieceDefiner.edit(PieceDefiner.java:1144)
</pre>

**Comment by BrentEaston** [comment] 2023-10-06 00:41
Duplicate of #12770

**Closed by BrentEaston** 2023-10-06 00:41 UTC
Labels: ABR
