### ISSUE TITLE
[??????] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "piece1" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11733] opened 2022-10-18 04:41 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | tdf01@nifty.com |
| Error Log | [42222 bytes](https://vassalengine.org/files/gh/1f4cc7c98d710bd0c4dd6a59b30f7887fb2363b7) |

<pre>I tried sorting the cards in the deck.

?????? v1.0 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "piece1" is null
 at VASSAL.build.module.map.deck.SortParameterComparator.compare(SortParameterComparator.java:52)
 at VASSAL.build.module.map.deck.SortParameterComparator.compare(SortParameterComparator.java:28)
 at java.base/java.util.TimSort.binarySort(TimSort.java:296)
 at java.base/java.util.TimSort.sort(TimSort.java:221)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:22
Duplicate of #11173

**Closed by BrentEaston** 2023-01-07 23:22 UTC
Labels: ABR
