### ISSUE TITLE
[MBT] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Plug the Gap.jpg:11,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12293] opened 2023-05-10 00:25 UTC
| ABR | |
|-----|-----|
| Version | 3.6.17 |
| Reporter |  |
| Error Log | [320906 bytes](https://vassalengine.org/files/gh/37d4bea31b395423ca17051b8ce751d9c51d3931) |

<pre>

MBT v1.1.8 3.6.17

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Plug the Gap.jpg:11,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:321)
</pre>

**Comment by BrentEaston** [comment] 2024-01-25 23:13
Duplicate of #10937

**Closed by BrentEaston** 2024-01-25 23:13 UTC
Labels: ABR
