### ISSUE TITLE
[Overlord/Killing Ground] NullPointerException: Cannot read field "parent" because "comp" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12945] opened 2023-11-29 06:55 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | peter.dietrich@waldmes.de |
| Error Log | [5810 bytes](https://vassalengine.org/files/gh/e6468f594f8f0136eebda03bdff005bbe33bbd03) |

<pre>I have copied the "Charts" Chart window menu. Trying to delete the "CRTv3" Map Windows creates this error. Tried it several times.

Overlord/Killing Ground v2.12 3.7.5

java.lang.NullPointerException: Cannot read field "parent" because "comp" is null
 at java.desktop/java.awt.Container.remove(Container.java:1290)
 at VASSAL.build.widget.MapWidget.remove(MapWidget.java:104)
 at VASSAL.configure.ConfigureTree.remove(ConfigureTree.java:1344)
 at VASSAL.configure.ConfigureTree.delete(ConfigureTree.java:1335)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:23
Duplicate of #12290

**Closed by BrentEaston** 2024-07-15 23:23 UTC
Labels: ABR
