### ISSUE TITLE
[Star Wars: Imperial Assault] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12915] opened 2023-11-18 22:21 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [5963 bytes](https://vassalengine.org/files/gh/afbd653ad99835059cbe7dbf5a714488125319ef) |

<pre>

Star Wars: Imperial Assault v1.13 3.7.5

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2576)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:273)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:247)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 02:14
Duplicate of #12033

**Closed by BrentEaston** 2023-12-09 02:14 UTC
Labels: ABR
