### ISSUE TITLE
[Binding of Isaac: Four Souls (New Game+)] NullPointerException: Cannot invoke "VASSAL.build.module.Map.placeOrMerge(VASSAL.counters.GamePiece, java.awt.Point)" because the return value of "VASSAL.build.module.map.DrawPile.getMap()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11590] opened 2022-07-17 06:38 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [30146 bytes](https://vassalengine.org/files/gh/a56691f7b0a5fc6291e02399891069cba39ef6d7) |

<pre>Rotating Clockwise?

Binding of Isaac: Four Souls (New Game+) v3.0 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.placeOrMerge(VASSAL.counters.GamePiece, java.awt.Point)" because the return value of "VASSAL.build.module.map.DrawPile.getMap()" is null
 at VASSAL.build.module.map.DrawPile.addToContents(DrawPile.java:1026)
 at VASSAL.build.module.map.DrawPile.addToContents(DrawPile.java:1013)
 at VASSAL.counters.ReturnToDeck.myKeyEvent(ReturnToDeck.java:170)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:492)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-09 21:19
Duplicate of #11360

**Closed by Cattlesquat** 2023-02-09 21:19 UTC
Labels: ABR
