### ISSUE TITLE
[Air & Armor] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\A-n-A Wurzburg-West.png:0,22@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12295] opened 2023-05-10 12:45 UTC
| ABR | |
|-----|-----|
| Version | 3.6.17 |
| Reporter | kevin.at.phoenix@gmail.com |
| Error Log | [17103 bytes](https://vassalengine.org/files/gh/d5c0f37698bffbb75c4c80b5f39ec4a70215b0a2) |

<pre>REplacing old maps with ready to print maps from developer

Air & Armor vPT K10 3.6.17

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\A-n-A Wurzburg-West.png:0,22@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment] 2024-01-25 23:13
Duplicate of #10937

**Closed by BrentEaston** 2024-01-25 23:13 UTC
Labels: ABR
