### ISSUE TITLE
[Korsun Pocket 2] IllegalStateException: Cannot insert a stack into another stack

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12316] opened 2023-05-20 22:15 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [14112 bytes](https://vassalengine.org/files/gh/db0de1bcdbfe970efdac1b76a3ffb2c5d7564f51) |

<pre>

Korsun Pocket 2 v1.1 3.6.19

java.lang.IllegalStateException: Cannot insert a stack into another stack
 at VASSAL.counters.Stack.insertChild(Stack.java:299)
 at VASSAL.counters.Stack.setState(Stack.java:639)
 at VASSAL.command.AddPiece.executeCommand(AddPiece.java:55)
 at VASSAL.command.Command.execute(Command.java:61)
</pre>

**Comment by BrentEaston** [comment] 2023-05-21 02:57
Duplicate of #11730

**Closed by BrentEaston** 2023-05-21 02:57 UTC
Labels: ABR
