### ISSUE TITLE
Right mouse menu on decks

### ISSUE THREAD

**Issue by UKSanctum** [vassalengine/vassal#10967] opened 2021-12-21 00:08 UTC
Vassal version: 3.6.2
Module: Gloomhaven_5Player 4.0
OS: Windows 10 64 bit

Issue:
Right clicking on Battle decks of player boards does not bring up the right mouse menu. Instead it triggers the first option of the right mouse menu.
![Gloomhaven_issue](https://user-images.githubusercontent.com/96448716/146841082-afa275a8-c1be-4a4b-9d83-8a6cb58371eb.JPG)

**Comment by Cattlesquat** [comment] 2021-12-22 21:05
Is the only option that's on the right click menu to "Draw Specific Cards"? If so that behavior is by design -- Vassal no longer opens a menu just to see if you want to draw specific cards, if "draw specific cards" is the only option on the menu. It just proceeds straight to offering you the cards.

If there are supposed to be OTHER options on that menu let me know, but when I looked in the module it didn't look like there were.

**Comment by Cattlesquat** [comment] 2021-12-31 16:40
Closed as "by design" unless further data indicating there should have been more than one option on the right click menu

**Closed** 2021-12-31 16:39 UTC
