### ISSUE TITLE
[Commands & Colors: Napoleonics] UnsupportedOperationException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12596] opened 2023-08-21 07:50 UTC
| ABR | |
|-----|-----|
| Version | 3.7.0-beta5 |
| Reporter | markben61@gmail.com |
| Error Log | [19574 bytes](https://vassalengine.org/files/gh/916758a8bf8073894f7f756651f0930a440542f4) |

<pre>Searched for $tcBonus$.

Vassal and the module had just been started up.

Commands & Colors: Napoleonics v4.2.0a37 3.7.0-beta5

java.lang.UnsupportedOperationException: null
 at java.base/java.util.AbstractList.add(AbstractList.java:155)
 at java.base/java.util.AbstractList.add(AbstractList.java:113)
 at VASSAL.counters.CounterGlobalKeyCommand.getPropertyList(CounterGlobalKeyCommand.java:235)
 at VASSAL.configure.ConfigureTree$SearchAction.checkSearchTarget(ConfigureTree.java:2280)
</pre>

**Comment by riverwanderer** [comment] 2023-08-21 07:51
Tried the same search again immediately and it worked fine.

**Comment by BrentEaston** [comment] 2023-08-21 08:14
Duplicate of #12595

**Closed by BrentEaston** 2023-08-21 08:14 UTC
Labels: ABR
