### ISSUE TITLE
[Star Wars X-Wing Miniatures Game] IllegalComponentStateException: component must be showing on the screen to determine its location

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12412] opened 2023-06-27 03:21 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [472605 bytes](https://vassalengine.org/files/gh/3081975b26ca2d32c6f1abc94b368b34f3d04b64) |

<pre>

Star Wars X-Wing Miniatures Game v9.4.0 3.6.19

java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
 at java.desktop/java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2113)
 at java.desktop/java.awt.Component.getLocationOnScreen(Component.java:2087)
 at java.desktop/javax.swing.JPopupMenu.show(JPopupMenu.java:961)
 at java.desktop/javax.swing.plaf.basic.BasicComboPopup.show(BasicComboPopup.java:235)
</pre>

**Comment by BrentEaston** [comment] 2023-06-27 04:26
Duplicate of #5378

**Closed by BrentEaston** 2023-06-27 04:26 UTC
Labels: ABR
