### ISSUE TITLE
[Pacific War 2] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11831] opened 2022-12-19 12:47 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter | spetras73@gmail.com |
| Error Log | [7725 bytes](https://vassalengine.org/files/gh/85130eafa3c56d8c4a35cd7e749bcfa2f9a784a5) |

<pre>

Pacific War 2 v2.00.025 3.6.9

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null
 at VASSAL.counters.Decorator.getOutermost(Decorator.java:525)
 at VASSAL.build.widget.PieceSlot.getLocalizedConfigureName(PieceSlot.java:609)
 at VASSAL.build.Widget$MyCellRenderer.getListCellRendererComponent(Widget.java:183)
 at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1444)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 06:15
Duplicate of #11813

**Closed by BrentEaston** 2023-01-07 06:16 UTC
Labels: ABR
