### ISSUE TITLE
[Gloomhaven] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11761] opened 2022-11-13 03:43 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [363745 bytes](https://vassalengine.org/files/gh/7d6d5a16fa97b203926dce6f9ba3085e4e34fbd3) |

<pre>

Gloomhaven v3.1 3.6.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 03:47
Duplicate of #5813

**Closed by BrentEaston** 2023-01-07 03:47 UTC
Labels: ABR
