### ISSUE TITLE
ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13332] opened 2024-05-16 20:45 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | sheridanj1024@gmail.com |
| Error Log | [21346 bytes](https://vassalengine.org/files/gh/47a2913d6482cca5032356f5320b77dfd3ecfdc7) |

<pre>tried downloading Vassal module OCS Blitzkrieg Legend.  Tried a few times, always stops at 21%.  A number of attempts.  Have downloaded numerous modules without problems.  Was able to download a different OCS module today without a problem.  

3.7.12

java.util.concurrent.ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 22:57
Duplicate of #12292

**Closed by BrentEaston** 2024-07-15 22:57 UTC
Labels: ABR
