### ISSUE TITLE
[Commands & Colors: Napoleonics V5] NoSuchMethodException: VASSAL.build.module.properties.ScenarioPropertiesOptionTab$TextConfig.<init>()

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13531] opened 2024-08-13 22:51 UTC
| ABR | |
|-----|-----|
| Version | 3.7.13 |
| Reporter | markben61@gmail.com |
| Error Log | [640004 bytes](https://vassalengine.org/files/gh/5c3bca9161168e46fda154f6ac555a8859059800) |

<pre>Error by clicking on a Scenarion Properties Options tab component within the Editor.

Commands & Colors: Napoleonics V5 v5.1.0a207 3.7.13

java.lang.NoSuchMethodException: VASSAL.build.module.properties.ScenarioPropertiesOptionTab$TextConfig.<init>()
 at java.base/java.lang.Class.getConstructor0(Class.java:3784)
 at java.base/java.lang.Class.getConstructor(Class.java:2452)
 at VASSAL.configure.AutoConfigurer.createConfigurer(AutoConfigurer.java:200)
 at VASSAL.configure.AutoConfigurer.<init>(AutoConfigurer.java:87)
</pre>

**Comment by BrentEaston** [comment] 2024-08-14 22:02
Duplicate of #13509

**Closed by BrentEaston** 2024-08-14 22:02 UTC
Labels: ABR
