### ISSUE TITLE
[Pandemic & all 3 expansions] IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11663] opened 2022-08-28 08:44 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [451726 bytes](https://vassalengine.org/files/gh/002831a8c4276d5680319231b8c8376a848973a4) |

<pre>I do not know what i was doing and i don't know how to make it happen again.  Sorry, y'all.  :-(

Pandemic & all 3 expansions v1.1 3.6.7

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
 at java.base/java.util.Objects.checkIndex(Objects.java:359)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 05:42
Duplicate of #11520

**Closed by BrentEaston** 2023-01-08 05:42 UTC
Labels: ABR
