### ISSUE TITLE
[Red Star Rising(???)] NoSuchMethodError: 'java.awt.TexturePaint rsr.RsrMapShader.getTexture()'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11715] opened 2022-10-06 16:50 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [25340 bytes](https://vassalengine.org/files/gh/a754d75a30e244622edb1152cbb3460804ab4643) |

<pre>

Red Star Rising(???) v4.0.8 3.6.7

java.lang.NoSuchMethodError: 'java.awt.TexturePaint rsr.RsrMapShader.getTexture()'
 at rsr.RsrMapShader.draw(RsrMapShader.java:160)
 at VASSAL.build.module.Map.drawDrawable(Map.java:2393)
 at VASSAL.build.module.Map.paintRegion(Map.java:2274)
 at VASSAL.build.module.Map.paintRegion(Map.java:2262)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:30
Duplicate of #11596

**Closed by BrentEaston** 2023-01-07 05:30 UTC
Labels: ABR
