### ISSUE TITLE
[Throne World] IndexOutOfBoundsException: Index: 1, Size: 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13077] opened 2024-01-19 01:30 UTC
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter | brettwjohnson@comcast.net |
| Error Log | [66026 bytes](https://vassalengine.org/files/gh/58944a27a1294aede2f1bdc6885b6f25e7f4730b) |

<pre>In Global Key Command window, clicked green "+" to Set Dynamic Properties in target pieces.  (Note Reference Manual does not address this capability of GKC)

Throne World v0.16 3.7.7

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
 at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:838)
 at java.base/java.util.ArrayList.add(ArrayList.java:510)
 at VASSAL.configure.ParameterListConfigurer.addEntry(ParameterListConfigurer.java:195)
 at VASSAL.configure.ConfigurableListController.lambda$new$2(ConfigurableListController.java:51)
</pre>

**Comment by BrentEaston** [comment] 2024-04-13 05:35
Duplicate of #13268

**Closed by BrentEaston** 2024-04-13 05:35 UTC
Labels: ABR
