### ISSUE TITLE
[Memoir '44] RuntimeException: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: Range [0, 3) out of bounds for length 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13411] opened 2024-06-22 14:50 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [24889 bytes](https://vassalengine.org/files/gh/0ea3f2406b30e898379e5066aeefdeff72332f57) |

<pre>

Memoir '44 v10.15 3.7.12

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: Range [0, 3) out of bounds for length 2
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Editor.<init>(Editor.java:60)
 at VASSAL.launch.Editor.main(Editor.java:53)
Caused by: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: Range [0, 3) out of bounds for length 2
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:36
Duplicate of #13429

**Closed by BrentEaston** 2024-07-15 23:36 UTC
Labels: ABR
