### ISSUE TITLE
[Eldritch Horror] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13286] opened 2024-04-20 22:25 UTC
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter |  |
| Error Log | [13562 bytes](https://vassalengine.org/files/gh/b6bb59119119cb4ecfa7217d32de1561ea6d8e3a) |

<pre>Testing module after  insert a new map window in a Extension

Eldritch Horror v1.0.1 3.7.10

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null
 at VASSAL.build.module.map.SetupStack.setup(SetupStack.java:274)
 at VASSAL.build.module.GameState.setup(GameState.java:566)
 at VASSAL.build.module.GameState$8.actionPerformed(GameState.java:273)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:33
Duplicate of #12869

**Closed by BrentEaston** 2024-07-16 06:33 UTC
Labels: ABR
