### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13159] opened 2024-02-17 03:51 UTC
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter |  |
| Error Log | [12559 bytes](https://vassalengine.org/files/gh/a571275e0695336ea4684f5eeb9eff0a2599f5a8) |

<pre>

3.7.8

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-02-21 03:01
Duplicate of #12346

**Closed by BrentEaston** 2024-02-21 03:01 UTC
Labels: ABR
