### ISSUE TITLE
[TTG] NullPointerException: Cannot invoke "VASSAL.configure.Configurer.getControls()" because "this.configurer" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13151] opened 2024-02-14 19:45 UTC
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter | eclectictllc@gmail.com |
| Error Log | [43762 bytes](https://vassalengine.org/files/gh/f1c7a57da3eefa58371ce5ad7484b12111580da8) |

<pre>Trying to edit a List Scenario Property on a Mac.

TTG v0.8.2 3.7.8

java.lang.NullPointerException: Cannot invoke "VASSAL.configure.Configurer.getControls()" because "this.configurer" is null
 at VASSAL.configure.PropertiesWindow.initialize(PropertiesWindow.java:119)
 at VASSAL.configure.PropertiesWindow.<init>(PropertiesWindow.java:60)
 at VASSAL.configure.EditPropertiesAction.actionPerformed(EditPropertiesAction.java:70)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by BrentEaston** [comment] 2024-02-14 19:55
Duplicate of #13152

**Closed by BrentEaston** 2024-02-14 19:55 UTC
Labels: ABR
