### ISSUE TITLE
ExecutionException: java.lang.IllegalStateException: bad type: 35

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12025] opened 2023-02-20 00:54 UTC
| ABR | |
|-----|-----|
| Version | 3.6.12 |
| Reporter |  |
| Error Log | [85116 bytes](https://vassalengine.org/files/gh/9aa3416199d9702f171cf3481b1e57389c7e8849) |

<pre>downloading vassal 3.5.12 new install

3.6.12

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: bad type: 35
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:519)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-20 15:28
duplicate of #11413

**Closed by Cattlesquat** 2023-02-20 15:28 UTC
Labels: ABR
