### ISSUE TITLE
ExecutionException: java.lang.IllegalStateException: bad type: 91

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11662] opened 2022-08-27 11:09 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [163355 bytes](https://vassalengine.org/files/gh/2bc5591f87f63e612761699a9b38da4cc3f24844) |

<pre>

3.6.7

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: bad type: 91
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-09 21:12
Duplicate of #11413

**Closed by Cattlesquat** 2023-02-09 21:12 UTC
Labels: ABR
