### ISSUE TITLE
[Empires in Harm] NullPointerException: Cannot invoke "VASSAL.build.module.map.boardPicker.board.mapgrid.GridContainer.removeGrid(VASSAL.build.module.map.boardPicker.board.MapGrid)" because "this.container" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11797] opened 2022-11-28 22:29 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [102973 bytes](https://vassalengine.org/files/gh/9a8e32f1483889c1124fdb03a3dba36855e28218) |

<pre>

Empires in Harm vV0.2 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.boardPicker.board.mapgrid.GridContainer.removeGrid(VASSAL.build.module.map.boardPicker.board.MapGrid)" because "this.container" is null
 at VASSAL.build.module.map.boardPicker.board.RegionGrid.removeFrom(RegionGrid.java:221)
 at VASSAL.configure.ConfigureTree.remove(ConfigureTree.java:1066)
 at VASSAL.configure.ConfigureTree.nodeUpdated(ConfigureTree.java:1339)
 at VASSAL.configure.EditPropertiesAction$1.windowClosed(EditPropertiesAction.java:77)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 04:27
Duplicate of #11797

**Closed by BrentEaston** 2023-01-08 04:27 UTC
Labels: ABR

**Comment by BrentEaston** [comment] 2023-01-08 04:28
Duplicate of #11394
