### ISSUE TITLE
[Starship Troopers] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11989] opened 2023-02-12 03:46 UTC
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter |  |
| Error Log | [13109 bytes](https://vassalengine.org/files/gh/18b6f8a1093751d5d15f419108f434496c35dec7) |

<pre>

Starship Troopers v1.4.0 3.6.11

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3419)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3405)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:446)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-17 19:57
Duplicate of #10886

**Closed by Cattlesquat** 2023-02-17 19:57 UTC
Labels: ABR
