### ISSUE TITLE
[Myrmes] IndexOutOfBoundsException: Index: 1, Size: 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13246] opened 2024-04-01 15:54 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter |  |
| Error Log | [45236 bytes](https://vassalengine.org/files/gh/0c371a5558d45abf0cd30798b12e312a0c6adf3d) |

<pre>

Myrmes v0.1 3.7.9

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
 at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:788)
 at java.base/java.util.ArrayList.add(ArrayList.java:513)
 at VASSAL.configure.ParameterListConfigurer.addEntry(ParameterListConfigurer.java:195)
 at VASSAL.configure.ConfigurableListController.lambda$new$2(ConfigurableListController.java:51)
</pre>

**Comment by BrentEaston** [comment] 2024-04-13 05:34
Duplicate of #13268

**Closed by BrentEaston** 2024-04-13 05:34 UTC
Labels: ABR
