### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11636] opened 2022-08-14 11:35 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [5595 bytes](https://vassalengine.org/files/gh/1db9d68718b2ba4a912b4f5129ceb5742ebfc3e0) |

<pre>

3.6.7

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by riverwanderer** [comment] 2022-09-28 04:52
Duplicate of https://github.com/vassalengine/vassal/issues/11408.

**Closed by riverwanderer** 2022-09-28 04:52 UTC
Labels: ABR
