### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12738] opened 2023-09-23 10:10 UTC
| ABR | |
|-----|-----|
| Version | 3.7.1 |
| Reporter |  |
| Error Log | [12972 bytes](https://vassalengine.org/files/gh/44afeef57c86bf4b0f7a93d36a950cf82bf1cb6a) |

<pre>

3.7.1

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2023-10-18 23:44
Duplicate of #12346

**Closed by BrentEaston** 2023-10-18 23:44 UTC
Labels: ABR
