### ISSUE TITLE
[Judgement - Test Realm] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11355] opened 2022-04-09 16:01 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | spleibowi@gmail.com |
| Error Log | [55062 bytes](https://vassalengine.org/files/gh/16c4ebb6c8286a4476ca1d8ae6e0e46376b9ebd0) |

<pre>I was attempting to load a mod.

Judgement - Test Realm vJECTR 2.0.9 3.6.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:35
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:35 UTC
Labels: ABR
