### ISSUE TITLE
[Warhammer Underworlds Mod] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13108] opened 2024-01-26 12:27 UTC
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter |  |
| Error Log | [2333489 bytes](https://vassalengine.org/files/gh/5a659c4f5eecb762317872e9cc7949da1ab7e023) |

<pre>

Warhammer Underworlds Mod v9.2 3.7.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2024-01-31 10:53
Duplicate of #5813

**Closed by BrentEaston** 2024-01-31 10:53 UTC
Labels: ABR
