### ISSUE TITLE
[Europe Engulfed] NoSuchMethodException: VASSAL.build.module.properties.ScenarioPropertiesOptionTab$TextConfig.<init>()

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13520] opened 2024-08-07 15:16 UTC
| ABR | |
|-----|-----|
| Version | 3.7.13 |
| Reporter |  |
| Error Log | [28024 bytes](https://vassalengine.org/files/gh/0e836d9a1608b748455defac59439e0241c01a2e) |

<pre>Clicked on Scenario Properties Option Tab

Europe Engulfed v3.4d 3.7.13

java.lang.NoSuchMethodException: VASSAL.build.module.properties.ScenarioPropertiesOptionTab$TextConfig.<init>()
 at java.base/java.lang.Class.getConstructor0(Class.java:3784)
 at java.base/java.lang.Class.getConstructor(Class.java:2452)
 at VASSAL.configure.AutoConfigurer.createConfigurer(AutoConfigurer.java:200)
 at VASSAL.configure.AutoConfigurer.<init>(AutoConfigurer.java:87)
</pre>

**Comment by BrentEaston** [comment] 2024-08-14 22:02
Duplicate of #13509

**Closed by BrentEaston** 2024-08-14 22:02 UTC
Labels: ABR
