### ISSUE TITLE
[Downfall of the Third Reich] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11845] opened 2022-12-29 13:27 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [19027 bytes](https://vassalengine.org/files/gh/2b29a82e7179a80928caa5a463ead0477a820e55) |

<pre>

Downfall of the Third Reich v1.0 3.6.9

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 03:44
Duplicate of #5813

**Closed** 2023-01-07 03:45 UTC
Labels: ABR
