### ISSUE TITLE
[?????] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13078] opened 2024-01-19 15:20 UTC
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter |  |
| Error Log | [32005 bytes](https://vassalengine.org/files/gh/d99c0fc6935dde0b3808cab3d1870f3d75d52ee7) |

<pre>

????? v1.0 3.7.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2024-01-21 02:12
Duplicate of #5813

**Closed by BrentEaston** 2024-01-21 02:12 UTC
Labels: ABR
