### ISSUE TITLE
[American Tank Ace EDIT] NullPointerException: Cannot read field "parent" because "comp" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13382] opened 2024-06-13 20:13 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | dave.ranck@gmail.com |
| Error Log | [60851 bytes](https://vassalengine.org/files/gh/fe16d412c3836f5bdbcc708ba61692b119af8503) |

<pre>Deleting a map window

American Tank Ace EDIT v1.2a 3.7.12

java.lang.NullPointerException: Cannot read field "parent" because "comp" is null
 at java.desktop/java.awt.Container.remove(Container.java:1290)
 at VASSAL.build.widget.MapWidget.remove(MapWidget.java:104)
 at VASSAL.configure.ConfigureTree.remove(ConfigureTree.java:1376)
 at VASSAL.configure.ConfigureTree.delete(ConfigureTree.java:1368)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:23
Duplicate of #12290

**Closed by BrentEaston** 2024-07-15 23:23 UTC
Labels: ABR
