### ISSUE TITLE
[Eldritch Horror] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13296] opened 2024-04-27 10:32 UTC
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter |  |
| Error Log | [40586 bytes](https://vassalengine.org/files/gh/6840e72f4daa2d3210343f0bc4d31032198614cd) |

<pre>

Eldritch Horror v1.0.1 3.7.10

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null
 at VASSAL.build.module.map.SetupStack.setup(SetupStack.java:274)
 at VASSAL.build.module.map.DrawPile.setup(DrawPile.java:1227)
 at VASSAL.build.module.GameState.setup(GameState.java:566)
 at VASSAL.build.module.GameState$8.actionPerformed(GameState.java:273)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:33
Duplicate of #12869

**Closed by BrentEaston** 2024-07-16 06:33 UTC
Labels: ABR
