### ISSUE TITLE
[Charge!] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11817] opened 2022-12-10 07:29 UTC
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter | resuece@gmail.com |
| Error Log | [6395 bytes](https://vassalengine.org/files/gh/01d24fdeed39e0e186423dbe92f2277dbafc3dcc) |

<pre>creando un peace

Charge! v3.2 3.6.8

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null
 at VASSAL.counters.Decorator.getOutermost(Decorator.java:525)
 at VASSAL.build.widget.PieceSlot.getLocalizedConfigureName(PieceSlot.java:609)
 at VASSAL.build.Widget$MyCellRenderer.getListCellRendererComponent(Widget.java:183)
 at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1444)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 06:16
Duplicate of #11813

**Closed by BrentEaston** 2023-01-07 06:16 UTC
Labels: ABR
