### ISSUE TITLE
[Banderin run] ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11819] opened 2022-12-11 21:02 UTC
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter | santiagodevoto2003@gmail.com |
| Error Log | [51315 bytes](https://vassalengine.org/files/gh/18c46cab605c1372aa8b8cefd435bff392f5608e) |

<pre>

Banderin run v0.0 3.6.8

java.util.concurrent.ExecutionException: java.lang.NullPointerException
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 22:26
Duplicate of #11820

**Closed by BrentEaston** 2023-01-07 22:26 UTC
Labels: ABR
