### ISSUE TITLE
[LRTG] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "this.crc" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12558] opened 2023-08-11 06:03 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | ltisseyre@free.fr |
| Error Log | [7619 bytes](https://vassalengine.org/files/gh/639895c50ddfa426a6eda5789bca063a34de2842) |

<pre>Je lançais le module Long Roads to Gettysburg 3.38

LRTG v0.0 3.6.19

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "this.crc" is null
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "this.crc" is null
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 02:52
Duplicate of  #12894

**Closed by BrentEaston** 2023-12-09 02:52 UTC
Labels: wontfix, Out of date VASSAL version
