### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11833] opened 2022-12-20 00:49 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter | rossjefferson2@gmail.com |
| Error Log | [2674 bytes](https://vassalengine.org/files/gh/8ba3f135a24f46b5e24ac18dadc699caa29adbbb) |

<pre>Both 3.6.8 and 3.6.9 when attempting to run Vassal I get this bug notifiation.  This has never happened before. 

3.6.9

java.lang.reflect.InvocationTargetException: null
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
 at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
 at VASSAL.launch.StartUp.initUIProperties(StartUp.java:107)
</pre>

**Comment by BrentEaston** [comment] 2023-01-08 03:00
Duplicate of #11240

**Closed by BrentEaston** 2023-01-08 03:00 UTC
Labels: ABR
