### ISSUE TITLE
ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13251] opened 2024-04-02 17:52 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter |  |
| Error Log | [91595 bytes](https://vassalengine.org/files/gh/73ae2f396c02560eaf174c0f155b22021a017914) |

<pre>just started to load

3.7.9

java.util.concurrent.ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-04-13 05:41
Duplicate of #12292

**Closed by BrentEaston** 2024-04-13 05:41 UTC
Labels: ABR
