### ISSUE TITLE
[QUICK] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11507] opened 2022-06-15 01:26 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | cpangracs@att.net |
| Error Log | [74326 bytes](https://vassalengine.org/files/gh/0d2cf51ead0d7d95ce4df290047320ecb15f2332) |

<pre>I was trying to move a property down in a piece property list while editing all the pieces in the deck

QUICK v0.1 3.6.7

java.lang.StackOverflowError: null
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 20:55
Duplicate of #11306

**Closed by Cattlesquat** 2023-02-10 20:55 UTC
Labels: ABR
