### ISSUE TITLE
ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12625] opened 2023-08-29 18:08 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | matthewsroot@gmail.com |
| Error Log | [13927 bytes](https://vassalengine.org/files/gh/444fe0428bdff248dcb47eee61da9747f554e113) |

<pre>Trying to run Aw-spi-v1-8. Did everything humanly possible.	

3.6.19

java.util.concurrent.ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:519)
</pre>

**Comment by BrentEaston** [comment] 2023-09-01 12:24
Duplicate of #12292

**Closed by BrentEaston** 2023-09-01 12:24 UTC
Labels: ABR
