### ISSUE TITLE
[Warhammer Underworlds Mod] ExecutionException: java.lang.IllegalArgumentException: Dimensions (width=2147483647 height=2147483647) are too large

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13443] opened 2024-07-04 21:50 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [2557754 bytes](https://vassalengine.org/files/gh/9a2a25b51fa919493b78407a4949c6d93de7a16e) |

<pre>

Warhammer Underworlds Mod v9.5.2 3.7.12

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
 at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:323)
 at VASSAL.tools.opcache.OpCache.get(OpCache.java:261)
 at VASSAL.tools.opcache.AbstractOpImpl.get(AbstractOpImpl.java:77)
 at VASSAL.tools.imageop.AbstractOpImpl.getImage(AbstractOpImpl.java:101)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:26
Duplicate of #13009

**Closed by BrentEaston** 2024-07-16 06:26 UTC
Labels: ABR
