### ISSUE TITLE
[Commands & Colors Samurai Battles] NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11674] opened 2022-09-04 07:55 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | markben61@gmail.com |
| Error Log | [2209243 bytes](https://vassalengine.org/files/gh/178aee8a3bbe3d4e95fb9d82784782d78c1d6b7e) |

<pre>Repro for #11673. 

Just copy a folder of GPs from main Global Properties folder to say Global Properties on the main map.
No duplicates of GPs already defined on the Main Map.

Commands & Colors Samurai Battles v1.50 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutablePropertiesContainer.addMutableProperty(String, VASSAL.build.module.properties.MutableProperty)" because "this.parent" is null
 at VASSAL.build.module.properties.MutableProperty$Impl.addTo(MutableProperty.java:98)
 at VASSAL.build.module.properties.GlobalProperty.addTo(GlobalProperty.java:213)
 at VASSAL.build.Builder.build(Builder.java:82)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
</pre>

**Comment by riverwanderer** [comment] 2022-09-04 08:00
Duplicate of #11673.

**Closed** 2022-09-04 19:52 UTC
Labels: ABR
