### ISSUE TITLE
IllegalArgumentException: node must be a TreeTableNode managed by this model

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12465] opened 2023-07-12 18:11 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | dvsmain@gmail.com |
| Error Log | [678577 bytes](https://vassalengine.org/files/gh/3038b847649c359cc49f399a446071e659708a9b) |

<pre>Remove a module (Tide of Iron) that appeared twice on my list, with the second listing only showing the Module Version and Description (the other fields were empty)

3.6.19

java.lang.IllegalArgumentException: node must be a TreeTableNode managed by this model
 at org.jdesktop.swingx.treetable.DefaultTreeTableModel.isLeaf(DefaultTreeTableModel.java:312)
 at java.desktop/javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1387)
 at java.desktop/javax.swing.plaf.metal.MetalTreeUI.paint(MetalTreeUI.java:190)
 at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
</pre>

**Comment by BrentEaston** [comment] 2023-07-27 21:29
Duplicate of #12438

**Closed by BrentEaston** 2023-07-27 21:29 UTC
Labels: ABR
