### ISSUE TITLE
[Land Power Brigade-DATE-P] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12950] opened 2023-12-01 16:02 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [32883 bytes](https://vassalengine.org/files/gh/4f89ce53e4a992dc3408cf133544b62c136d6fe1) |

<pre>

Land Power Brigade-DATE-P vCGSC 0.3 3.7.5

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 00:55
Duplicate of #5813

**Closed by BrentEaston** 2023-12-09 00:55 UTC
Labels: ABR
