### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12875] opened 2023-11-06 12:11 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [4521 bytes](https://vassalengine.org/files/gh/8891fa2ec2f9108d7f1942258b759ad1af5f6cf1) |

<pre>

3.7.5

java.lang.ExceptionInInitializerError: null
 at VASSAL.launch.ModuleManager.launch(ModuleManager.java:384)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
</pre>

**Comment by BrentEaston** [comment] 2023-12-09 03:31
Duplicate of #12849

**Closed by BrentEaston** 2023-12-09 03:31 UTC
Labels: ABR
