### ISSUE TITLE
OldMat information not set correctly after Send to Location

### ISSUE THREAD

**Issue by assaultdoor** [vassalengine/vassal#11884] opened 2023-01-10 00:10 UTC
This is on 3.6.9 running on MacOS.

Things like OldMatID and OldMatBasicName appear to be cleared after a Send to Location.

Steps to reproduce:
1) Create a mat.
2) Create a piece that has the Mat Cargo property.
3) Add a Send to Location to the piece with the Mat Cargo property.
4) Add a text label to the piece with the Mat Cargo that shows the values of OldMatBasicName, OldMatPieceName, OldMatID, OldMatOffsetX, and OldMatOffsetY
5) Run the game, put the cargo on the mat, and activate the Send to Location property.
Expected Result: The text label should have values for all those things.
Actual Result: the text label has no values for any of them.

**Comment by BrentEaston** [comment] 2023-01-10 03:57
I suspect they are being cleared because the piece is no Cargo. The problem is, if these properties aren't cleared now, when do they get cleared?

@Cattlesquat Are we clearing the OldMat properties if a piece doesn't land on a Mat?

**Comment by assaultdoor** [comment] 2023-01-10 04:58
Update: OldMat properties are always cleared if Mat Cargo is below Send to Location, whether it lands on another mat or not. Mat Cargo should be above Send to Location, but I accidentally had it down lower. I had assumed that Send to Location and moving by click-and-drag would work exactly the same way, but that's clearly not the case.

Please don't clear OldMat information if a piece is no longer cargo. Knowing that a piece just left a mat is incredibly useful for all sorts of things.

**Comment by BrentEaston** [comment] 2023-01-10 05:04
I'll get our Mat expert @Cattlesquat to comment on these issues.

**Comment by Cattlesquat** [comment] 2023-02-09 22:00
@BrentEaston This is what Send-to-Location does (screenshot) --  it passes itself (the *trait* not the *outermost piece*) to `putOldProperties` -- which is ultimately resulting in the only-cargo-below-send situation. Question is, should I:
(a) alter the call to putOldProperties to always use the outermost piece?
(b) alter putOldProperties to itself just always go to the outermost piece before starting its parade (this is my guess)?
(c) Something else more devious that you think of?

![image](https://user-images.githubusercontent.com/3742246/217948609-214a53ca-cdba-4e73-b54e-1b7cbe725141.png)

**Comment by BrentEaston** [comment] 2023-02-10 00:41
@Cattlesquat I think when I wrote Decorator,.putOldProperties, all the properties it handled where supplied by BasicPiece, so for efficiency, there was need to get the outermost. I had not envisaged it being used for more outer properties.

I would leave the calls to outOldProperties the same and change Decorator.putOldProperties to add a getOuterMost() call inside the isMatSupport() If statement so we only do it if Mats are actually being used. If the supplied trait is already the Outermost, getOuterMost() is super efficient anyway.

**Comment by Cattlesquat** [comment] 2023-02-10 16:00
This one should be fixed by #11975, in next version of Vassal released

**Closed** 2023-02-12 15:09 UTC
Labels: bug
