### ISSUE TITLE
[Nieuwpoort 1600] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Mappa nuova con turni.png:3,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12285] opened 2023-05-07 16:13 UTC
| ABR | |
|-----|-----|
| Version | 3.6.17 |
| Reporter |  |
| Error Log | [25999 bytes](https://vassalengine.org/files/gh/439a424ea0df30c5ed74f1cd37056103e97f5363) |

<pre>Just adding hex grid to an image
png

Nieuwpoort 1600 v1.0 3.6.17

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Mappa nuova con turni.png:3,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment] 2024-01-25 23:13
Duplicate of #10937

**Closed by BrentEaston** 2024-01-25 23:13 UTC
Labels: ABR
