### ISSUE TITLE
[????] NullPointerException: Cannot invoke "String.length()" because "text" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12926] opened 2023-11-23 06:03 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [18901 bytes](https://vassalengine.org/files/gh/87b5b8e953067608fafbdf750b63fbe816599752) |

<pre>

???? v0.0 3.7.5

java.lang.NullPointerException: Cannot invoke "String.length()" because "text" is null
 at java.desktop/javax.swing.colorchooser.ValueFormatter$1.replace(ValueFormatter.java:63)
 at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:691)
 at java.desktop/javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1335)
 at java.desktop/javax.swing.text.JTextComponent.replaceInputMethodText(JTextComponent.java:4836)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:18
Duplicate of #12586

**Closed by BrentEaston** 2024-07-15 23:18 UTC
Labels: ABR
