### ISSUE TITLE
ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13016] opened 2023-12-26 12:38 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [1113715 bytes](https://vassalengine.org/files/gh/6afac209dafe803992ba7a3f82952d1088dbcb79) |

<pre>

3.7.6

java.util.concurrent.ExecutionException: java.io.IOException: Probably ran out of memory. Tiling failed with return value == 2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-01-03 22:37
Duplicate of #12292

**Closed by BrentEaston** 2024-01-03 22:37 UTC
Labels: ABR
