### ISSUE TITLE
[The Spanish Ulcer 1808-1814] NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "VASSAL.build.module.map.DrawPile.getAttributeValueString(String)" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11830] opened 2022-12-18 22:35 UTC
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter | quiqueesparrago@hotmail.com |
| Error Log | [12280 bytes](https://vassalengine.org/files/gh/7b165eece1ddb8727a4d4086d8bdcf09dbd973f7) |

<pre>I want to add a deck (named Attrition cards) in an "older" Scenario

The Spanish Ulcer 1808-1814 vv11.3     2-players 3.6.9

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "VASSAL.build.module.map.DrawPile.getAttributeValueString(String)" is null
 at VASSAL.build.module.GameRefresher.execute(GameRefresher.java:478)
 at VASSAL.build.module.PredefinedSetup.refresh(PredefinedSetup.java:309)
 at VASSAL.configure.RefreshPredefinedSetupsDialog.refreshPredefinedSetups(RefreshPredefinedSetupsDialog.java:242)
 at VASSAL.configure.RefreshPredefinedSetupsDialog.lambda$initComponents$0(RefreshPredefinedSetupsDialog.java:82)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 23:12
Duplicate of #11823

**Closed by BrentEaston** 2023-01-07 23:12 UTC
Labels: ABR
