### ISSUE TITLE
ExecutionException: java.io.IOException: Cannot delete file: C:\Users\david\AppData\Local\VASSAL\tiles\4293729723a12383d71f76c082252458346a2fdc

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11896] opened 2023-01-13 09:46 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter | david.61@hotmail.co.uk |
| Error Log | [10402 bytes](https://vassalengine.org/files/gh/190168182b0856f11318191f9f3ed010e4d88b8e) |

<pre>opening module

3.6.10

java.util.concurrent.ExecutionException: java.io.IOException: Cannot delete file: C:\Users\david\AppData\Local\VASSAL\tiles\4293729723a12383d71f76c082252458346a2fdc
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 18:46
Duplicate of #10627

**Closed by Cattlesquat** 2023-02-10 18:46 UTC
Labels: ABR
