### ISSUE TITLE
[Star Wars X-Wing Miniatures Game] IllegalComponentStateException: component must be showing on the screen to determine its location

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13494] opened 2024-07-20 15:37 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [469547 bytes](https://vassalengine.org/files/gh/2b243f1c35bb4181bcd604fd00fc57606135769f) |

<pre>I think it was checking to see if I had missing files.

Star Wars X-Wing Miniatures Game v9.4.0 3.7.12

java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
 at java.desktop/java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2113)
 at java.desktop/java.awt.Component.getLocationOnScreen(Component.java:2087)
 at java.desktop/javax.swing.JPopupMenu.show(JPopupMenu.java:982)
 at java.desktop/javax.swing.plaf.basic.BasicComboPopup.show(BasicComboPopup.java:235)
</pre>

**Comment by BrentEaston** [comment] 2024-07-22 22:44
Duplicate of #5378

**Closed by BrentEaston** 2024-07-22 22:44 UTC
Labels: ABR
