### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12986] opened 2023-12-12 06:36 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | 22693316@qq.com |
| Error Log | [11757 bytes](https://vassalengine.org/files/gh/5b015195957209bd8a5efa5c0980a76d845c3aea) |

<pre>

3.7.5

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2023-12-13 20:04
Duplicate of #12346

**Closed by BrentEaston** 2023-12-13 20:04 UTC
Labels: ABR
