### ISSUE TITLE
[Combat Commander: Europe] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13333] opened 2024-05-16 22:55 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [61892 bytes](https://vassalengine.org/files/gh/89ce32ca7def06e481f1849574da803e624869aa) |

<pre>

Combat Commander: Europe v2.5 3.7.12

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2577)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:274)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:248)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:25
Duplicate of #12033

**Closed by BrentEaston** 2024-07-16 06:25 UTC
Labels: ABR
