### ISSUE TITLE
[Neuroshima Hex 3.0] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12870] opened 2023-11-02 15:21 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [29156 bytes](https://vassalengine.org/files/gh/0b13afd1fad9729c10290f28a49f9ae358a295bb) |

<pre>

Neuroshima Hex 3.0 v2.3 3.7.5

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-11-19 20:43
Duplicate of #5813

**Closed by BrentEaston** 2023-11-19 20:43 UTC
Labels: ABR
