### ISSUE TITLE
[Commands & Colors: Napoleonics] UnsupportedOperationException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12597] opened 2023-08-21 08:08 UTC
| ABR | |
|-----|-----|
| Version | 3.7.0-beta5 |
| Reporter | markben61@gmail.com |
| Error Log | [38116 bytes](https://vassalengine.org/files/gh/316a0ccaf56162ee3031ce668a4427db536eb874) |

<pre>same as previous... first search "$tcBonus$" 

Commands & Colors: Napoleonics v4.2.0a37 3.7.0-beta5

java.lang.UnsupportedOperationException: null
 at java.base/java.util.AbstractList.add(AbstractList.java:155)
 at java.base/java.util.AbstractList.add(AbstractList.java:113)
 at VASSAL.counters.CounterGlobalKeyCommand.getPropertyList(CounterGlobalKeyCommand.java:235)
 at VASSAL.configure.ConfigureTree$SearchAction.checkSearchTarget(ConfigureTree.java:2280)
</pre>

**Comment by riverwanderer** [comment] 2023-08-21 08:10
Correction, this time it was a search on "tcBonus", without the dollars.

**Comment by BrentEaston** [comment] 2023-08-21 08:14
Duplicate of #12595

**Closed by BrentEaston** 2023-08-21 08:14 UTC
Labels: ABR
