### ISSUE TITLE
[Spirit Island] NullPointerException: Cannot invoke "VASSAL.counters.Deck$CountExpression.getName()" because "this.countExpressions[i]" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12643] opened 2023-09-03 22:47 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | ryance@sunybroome.edu |
| Error Log | [416928 bytes](https://vassalengine.org/files/gh/a8a9be6f56c1e00d2e9500e5213169ce7a717598) |

<pre>I just used Cmd+X to cut an expression to count out of a deck.

Spirit Island v4.5 beta 4 (Nature Incarnate+Horizons spirits with automated setup) 3.6.19

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.Deck$CountExpression.getName()" because "this.countExpressions[i]" is null
 at VASSAL.counters.Deck.setCountExpressions(Deck.java:879)
 at VASSAL.build.module.map.DrawPile.setAttribute(DrawPile.java:771)
 at VASSAL.configure.AutoConfigurer.propertyChange(AutoConfigurer.java:243)
 at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
</pre>

**Comment by BrentEaston** [comment] 2023-09-05 05:32
Duplicate of #12644

**Closed by BrentEaston** 2023-09-05 05:32 UTC
Labels: ABR
