### ISSUE TITLE
[Jeu de Bataille de la Terre du Milieu] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12918] opened 2023-11-20 21:55 UTC
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [316214 bytes](https://vassalengine.org/files/gh/780f1ffc264e878cd26b93e79292108effd26abc) |

<pre>

Jeu de Bataille de la Terre du Milieu v1.6 3.7.5

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-11-23 23:53
Duplicate of #5813

**Closed by BrentEaston** 2023-11-23 23:53 UTC
Labels: ABR
