### ISSUE TITLE
[WS - Fall Blau] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10331] opened 2021-08-20 18:22 UTC
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | peter.dietrich@waldmes.de |
| Error Log | [2505 bytes](http://www.vassalengine.org/files/gh/42dc0a1cff6a43c6c56772fdbf0ea53ea644c819) |

<pre>I tried to load an image into a mod. No Image type appeared, and by closing the menu i got this error.

WS - Fall Blau v007.3 3.5.8

java.lang.NullPointerException: null
 at java.base/java.io.File.<init>(File.java:278)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.filenameFilterCallback(GtkFileDialogPeer.java:107)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.run(Native Method)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.showNativeDialog(GtkFileDialogPeer.java:195)
</pre>

**Comment by BrentEaston** [comment] 2021-08-21 02:33
Duplicate of #10330

**Closed by BrentEaston** 2021-08-21 02:33 UTC
Labels: ABR
