### ISSUE TITLE
[Red Star Rising(???)] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11801] opened 2022-11-30 11:17 UTC
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter |  |
| Error Log | [18717 bytes](https://vassalengine.org/files/gh/f736a2e59a5f241e8d0dca2bc9a2acf25434995c) |

<pre>

Red Star Rising(???) v4.0.8 3.6.8

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 03:47
Duplicate of #5813

**Closed by BrentEaston** 2023-01-07 03:47 UTC
Labels: ABR
