### ISSUE TITLE
[Starship Troopers -Lazzar 2ND  Map-Dice edit  LoneStar FHB modified] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11751] opened 2022-11-07 21:03 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [7513 bytes](https://vassalengine.org/files/gh/251cae6711bea4644ee992e4f4b6c17c702340f1) |

<pre>

Starship Troopers -Lazzar 2ND  Map-Dice edit  LoneStar FHB modified v1.3.3.1 3.6.7

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3420)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3406)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:440)
</pre>

**Comment by BrentEaston** [comment] 2023-01-09 22:10
Duplicate of #10886

**Closed by BrentEaston** 2023-01-09 22:10 UTC
Labels: ABR
