### ISSUE TITLE
[WiF CE Maps and Units Combo] NoSuchMethodException: VASSAL.build.module.properties.ScenarioPropertiesOptionTab$TextConfig.<init>()

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13513] opened 2024-08-02 07:57 UTC
| ABR | |
|-----|-----|
| Version | 3.7.13 |
| Reporter | donsgeneralstuff@exemail.com.au |
| Error Log | [6382 bytes](https://vassalengine.org/files/gh/868fce8f80001c8b50beb04fe48ffded2eea5e7d) |

<pre>Clicking on a Scenarion Properties Options Tab. Error happens every time I do that for the first time in an editing session. I have not reported it until now as I restarted Vassal and relaunched the module in edit mode to minimise the error log content to just this error.

WiF CE Maps and Units Combo v1.41 3.7.13

java.lang.NoSuchMethodException: VASSAL.build.module.properties.ScenarioPropertiesOptionTab$TextConfig.<init>()
 at java.base/java.lang.Class.getConstructor0(Class.java:3784)
 at java.base/java.lang.Class.getConstructor(Class.java:2452)
 at VASSAL.configure.AutoConfigurer.createConfigurer(AutoConfigurer.java:200)
 at VASSAL.configure.AutoConfigurer.<init>(AutoConfigurer.java:87)
</pre>

**Comment by BrentEaston** [comment] 2024-08-14 22:02
Duplicate of #13509

**Closed by BrentEaston** 2024-08-14 22:02 UTC
Labels: ABR
