### ISSUE TITLE
[Europe Engulfed] NullPointerException: Cannot invoke "VASSAL.configure.Configurer.getControls()" because "this.configurer" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13025] opened 2023-12-29 17:25 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter | brettwjohnson@comcast.net |
| Error Log | [6169 bytes](https://vassalengine.org/files/gh/6d93ed561683e733cd48743df3fb736cb663baf6) |

<pre>Duplicated a LIST SCENARIO PROPERTY in SCENARIO PROPERTIES OPTION TAB

Europe Engulfed v3.3.0k 3.7.6

java.lang.NullPointerException: Cannot invoke "VASSAL.configure.Configurer.getControls()" because "this.configurer" is null
 at VASSAL.configure.PropertiesWindow.initialize(PropertiesWindow.java:119)
 at VASSAL.configure.PropertiesWindow.<init>(PropertiesWindow.java:60)
 at VASSAL.configure.ConfigureTree$AddAction$1.<init>(ConfigureTree.java:1182)
 at VASSAL.configure.ConfigureTree$AddAction.doIt(ConfigureTree.java:1182)
</pre>

**Comment by BrentEaston** [comment] 2024-02-21 03:06
Duplicate of #13152

**Closed by BrentEaston** 2024-02-21 03:06 UTC
Labels: ABR
