### ISSUE TITLE
[VSQL] NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12533] opened 2023-08-06 20:04 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | scott@squadleaderacademy.org |
| Error Log | [19487 bytes](https://vassalengine.org/files/gh/ef0aa13358167a06b409ae737e4ddad1bcc511ec) |

<pre>Refresh GIA counters from extension 9.2 to 9.3.
The refresh changed US leaders to German Leaders
Manually replace and graveyard german counters
Delete German counters from graveyard.
threw error.

VSQL v4.3.6 3.6.19

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:264)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:246)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-08-06 23:22
Duplicate of #12494

**Closed by BrentEaston** 2023-08-06 23:22 UTC
Labels: ABR
