### ISSUE TITLE
[Twilight Struggle] NullPointerException: Cannot invoke "javax.swing.KeyStroke.equals(Object)" because the return value of "VASSAL.counters.KeyCommand.getKeyStroke()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12281] opened 2023-05-05 12:12 UTC
| ABR | |
|-----|-----|
| Version | 3.6.17 |
| Reporter |  |
| Error Log | [17568 bytes](https://vassalengine.org/files/gh/b0db2f0bd453d4f3f572282171f3eaa47b89accf) |

<pre>

Twilight Struggle v3.0.11 3.6.17

java.lang.NullPointerException: Cannot invoke "javax.swing.KeyStroke.equals(Object)" because the return value of "VASSAL.counters.KeyCommand.getKeyStroke()" is null
 at ca.mkiefte.Ops.getKeyCommands(Ops.java:182)
 at VASSAL.counters.Decorator.getProperty(Decorator.java:161)
 at ca.mkiefte.Ops.getProperty(Ops.java:144)
 at VASSAL.counters.Decorator.getKeyCommands(Decorator.java:452)
</pre>

**Comment by BrentEaston** [comment] 2023-09-01 12:23
Duplicate of #11874

**Closed by BrentEaston** 2023-09-01 12:23 UTC
Labels: ABR
