### ISSUE TITLE
[Warhammer Diskwars] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11384] opened 2022-04-21 10:52 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [60205 bytes](https://vassalengine.org/files/gh/e3dd952215a25b0232ede240bde93fc33a97a27d) |

<pre>

Warhammer Diskwars v3.0 3.6.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2022-06-29 01:36
Duplicate of #5813

**Closed by BrentEaston** 2022-06-29 01:36 UTC
Labels: ABR
