### ISSUE TITLE
[Pacific War] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12186] opened 2023-04-05 19:02 UTC
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter | michael_clark@charter.net |
| Error Log | [7772 bytes](https://vassalengine.org/files/gh/5e448a1b60a267c58f9a1ff8d2002e27695df844) |

<pre>Look for a game to join - Pacific War

Pacific War v1.0 3.6.15

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-04-18 01:52
Duplicate of #5813

**Closed by BrentEaston** 2023-04-18 01:52 UTC
Labels: ABR
