### ISSUE TITLE
[Conquest of Paradise] IllegalArgumentException: Width (0) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12863] opened 2023-10-28 10:27 UTC
| ABR | |
|-----|-----|
| Version | 3.7.4 |
| Reporter | macko.mar@gmail.com |
| Error Log | [5184 bytes](https://vassalengine.org/files/gh/697334a5049b1ed13cb32d3ff23388c9f1e83a11) |

<pre>My Kubuntu locked my screen while having the Conquest of Paradise open and I unlocked the screen.

Conquest of Paradise v1.4.2 3.7.4

java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
 at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:75)
 at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122)
 at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:305)
 at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:239)
</pre>

**Comment by BrentEaston** [comment] 2023-11-01 21:36
Duplicate of #12489

**Closed by BrentEaston** 2023-11-01 21:36 UTC
Labels: ABR
