### ISSUE TITLE
[Commands & Colors: Napoleonics V5] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13225] opened 2024-03-25 18:18 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter |  |
| Error Log | [17552 bytes](https://vassalengine.org/files/gh/b7be8c38bdd1763f2086e715caa57bc07c97b2e3) |

<pre>cargando un escenario

Commands & Colors: Napoleonics V5 v5.0.0beta4 3.7.9

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
 at VASSAL.build.module.GameState$12.compare(GameState.java:1582)
 at VASSAL.build.module.GameState$12.compare(GameState.java:1568)
 at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
 at java.base/java.util.TimSort.sort(TimSort.java:234)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 22:25
Duplicate of #13339

**Closed by BrentEaston** 2024-07-16 22:25 UTC
Labels: ABR, Out of date VASSAL version
