### ISSUE TITLE
[VSQL] NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12379] opened 2023-06-18 13:33 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | Montyjasper55@gmail.com |
| Error Log | [9743 bytes](https://vassalengine.org/files/gh/212faf1b78b8b7966f1f74e2f9048090ff086106) |

<pre>I was moving the units in the graveyard

VSQL v4.3.5 3.6.19

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.PieceMover.getBreachedThreshold()" because the return value of "VASSAL.build.module.Map.getPieceMover()" is null
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:264)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:246)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment] 2023-07-26 07:00
Duplicate of #12494

**Closed by BrentEaston** 2023-07-26 07:00 UTC
Labels: ABR
