### ISSUE TITLE
ExecutionException: java.io.IOException: return value == 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11740] opened 2022-10-28 16:02 UTC
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | kevin.shewfelt@aol.com |
| Error Log | [23857 bytes](https://vassalengine.org/files/gh/1f197021e9af2fc08d2054b445eca99cbbbf2b36) |

<pre>

3.6.7

java.util.concurrent.ExecutionException: java.io.IOException: return value == 1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:511)
</pre>

**Comment by BrentEaston** [comment] 2023-01-07 05:24
Duplicate of #9990

**Closed by BrentEaston** 2023-01-07 05:24 UTC
Labels: ABR
