### ISSUE TITLE
[VASL] IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13014] opened 2023-12-25 18:19 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter |  |
| Error Log | [308864 bytes](https://vassalengine.org/files/gh/a5a688caf55b8670ff5bf9bf022b421bea18f2a6) |

<pre>

VASL v6.6.7 3.7.6

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
 at java.base/java.util.Objects.checkIndex(Objects.java:385)
</pre>

**Comment by BrentEaston** [comment] 2023-12-27 21:48
Duplicate of #12981

**Closed by BrentEaston** 2023-12-27 21:48 UTC
Labels: ABR
