### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12012] opened 2023-02-16 00:53 UTC
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter |  |
| Error Log | [10334 bytes](https://vassalengine.org/files/gh/23140507caf9d716840656c5f96c0338caa5fb50) |

<pre>

Twilight Struggle 3.1 v3.1.2 3.6.11

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2023-02-16 01:01
Duplicate of #11874

**Closed by BrentEaston** 2023-02-16 01:01 UTC
Labels: ABR
