### ISSUE TITLE
[SF3D original] NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "string" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13465] opened 2024-07-14 10:11 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [17401 bytes](https://vassalengine.org/files/gh/362b2eefd648ebb6f960e0972b532b28880e4168) |

<pre>

SF3D original v0.3 3.7.12

java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "string" is null
 at VASSAL.build.module.gamepieceimage.GamePieceImage$ImageNameFilter.clean(GamePieceImage.java:581)
 at VASSAL.build.module.gamepieceimage.GamePieceImage$ImageNameFilter.replace(GamePieceImage.java:631)
 at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:691)
 at java.desktop/javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1335)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:05
Duplicate of #13365

**Closed by BrentEaston** 2024-07-15 23:05 UTC
Labels: ABR
