### ISSUE TITLE
[Twilight Struggle] NullPointerException: Cannot invoke "javax.swing.KeyStroke.equals(Object)" because the return value of "VASSAL.counters.KeyCommand.getKeyStroke()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11363] opened 2022-04-12 23:56 UTC
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | marinho.wagner@yahoo.com.br |
| Error Log | [23960 bytes](https://vassalengine.org/files/gh/83db60f7940d45b33839bbd55791814161080cb4) |

<pre>

Twilight Struggle v3.0.10a 3.6.6

java.lang.NullPointerException: Cannot invoke "javax.swing.KeyStroke.equals(Object)" because the return value of "VASSAL.counters.KeyCommand.getKeyStroke()" is null
 at ca.mkiefte.Ops.getKeyCommands(Ops.java:176)
 at VASSAL.counters.Decorator.getProperty(Decorator.java:163)
 at ca.mkiefte.Ops.getProperty(Ops.java:144)
 at VASSAL.counters.Decorator.getKeyCommands(Decorator.java:454)
</pre>

**Comment by Cattlesquat** [comment] 2023-02-10 22:05
Duplicate of #11874

**Closed by Cattlesquat** 2023-02-10 22:05 UTC
Labels: ABR
