### ISSUE TITLE
ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == -1073741515

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13256] opened 2024-04-05 22:07 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | kigghia@gmail.com |
| Error Log | [8751 bytes](https://vassalengine.org/files/gh/36180ff87684849d8de980dcd930e73634ab010a) |

<pre>every time i open a module

just tried to increase the max heap limit , no effects

3.7.9

java.util.concurrent.ExecutionException: java.io.IOException: Possibly ran out of memory. Tiling failed with return value == -1073741515
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-04-13 05:41
Duplicate of #12292

**Closed by BrentEaston** 2024-04-13 05:41 UTC
Labels: ABR
