### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11898] opened 2023-01-14 17:30 UTC
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter | janardi815@gmail.com |
| Error Log | [4898 bytes](https://vassalengine.org/files/gh/4a78c6947cc2cc81ca3237ee720509bc3c11ccba) |

<pre>Was just loading Twilight Struggle 3.1 module in Vassal 3.6.10 and got this bug!

Twilight Struggle 3.1 v3.1.2 3.6.10

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2023-01-15 09:28
Duplicate of #11874

**Closed by BrentEaston** 2023-01-15 09:28 UTC
Labels: ABR
