### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12740] opened 2023-09-24 04:27 UTC
| ABR | |
|-----|-----|
| Version | 3.7.1 |
| Reporter | wadewan@outlook.com |
| Error Log | [2668 bytes](https://vassalengine.org/files/gh/e31563ca86682552fe731f92be6980e241008a79) |

<pre>Just trying to open this new version.  The previous version quick working and told me this newer version was available. I tried uninstalling new version and reinstalling older version and it gives me the same issue.   NO PRIOR PROBLEMS unitl this popped up.

3.7.1

java.lang.reflect.InvocationTargetException: null
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
 at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
 at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
 at VASSAL.launch.StartUp.initUIProperties(StartUp.java:107)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:36
Duplicate of #11240

**Closed by BrentEaston** 2024-07-16 06:36 UTC
Labels: ABR
