### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13162] opened 2024-02-18 08:37 UTC
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter | Wang21010620080119@163.com |
| Error Log | [12421 bytes](https://vassalengine.org/files/gh/62010c210890f2614b164aee2d9ce1236e42ea91) |

<pre>open  a moudle ....
To make it happen again , you should use my computer to open VASSAL , and you will see the dialog

3.7.8

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-02-21 03:01
Duplicate of #12346

**Closed by BrentEaston** 2024-02-21 03:01 UTC
Labels: ABR
