### ISSUE TITLE
[Commands & Colors: Napoleonics] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13206] opened 2024-03-17 15:14 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter |  |
| Error Log | [53516 bytes](https://vassalengine.org/files/gh/e7923aac19f5faabe3d1df1205fddc31d14a4e29) |

<pre>

Commands & Colors: Napoleonics v4.1.16 3.7.9

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 22:25
Duplicate of #13339

**Closed by BrentEaston** 2024-07-16 22:25 UTC
Labels: ABR
