### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13020] opened 2023-12-27 15:27 UTC
| ABR | |
|-----|-----|
| Version | 3.7.6 |
| Reporter | finkmicha@hotmail.com |
| Error Log | [9401 bytes](https://vassalengine.org/files/gh/a288028fb3ce25edfb55b3b17a4b8f3fd0baf044) |

<pre>Opening Twilight Struggle 3.1

Twilight Struggle 3.1 v3.1.2 3.7.6

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2023-12-27 21:22
Duplicate of #11874

**Closed by BrentEaston** 2023-12-27 21:22 UTC
Labels: ABR
