### ISSUE TITLE
[Formula Dé] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12391] opened 2023-06-22 01:39 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [12882 bytes](https://vassalengine.org/files/gh/7f0e75416d9e10e65379902b71d2924666df187b) |

<pre>

Formula Dé v3.0 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2023-06-24 10:51
Duplicate of #5813

**Closed by BrentEaston** 2023-06-24 10:51 UTC
Labels: ABR
