### ISSUE TITLE
[Vijayanagara] ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13221] opened 2024-03-21 12:24 UTC
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | bcallen56@yahoo.com |
| Error Log | [22868 bytes](https://vassalengine.org/files/gh/2915a25e1a4b5885fc2bb07230b5aaf66411d740) |

<pre>Playback of vlog file.

Happened before when playing a vlog from the same player.

Vijayanagara v1.0 3.7.9

java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
 at VASSAL.build.module.SpecialDiceButton.setFormat(SpecialDiceButton.java:224)
 at VASSAL.build.module.SpecialDiceButton$ShowResults.executeCommand(SpecialDiceButton.java:644)
 at VASSAL.command.Command.execute(Command.java:61)
 at VASSAL.build.module.BasicLogger.step(BasicLogger.java:360)
</pre>

**Comment by BrentEaston** [comment] 2024-04-13 05:49
Duplicate of #13203

**Closed by BrentEaston** 2024-04-13 05:49 UTC
Labels: ABR
