### ISSUE TITLE
[Commands & Colors Ancients] NullPointerException: Cannot invoke "VASSAL.counters.Deck.getOrderedPieces()" because the return value of "VASSAL.build.module.map.DrawPile.getDeck()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10562] opened 2021-10-17 17:29 UTC
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [957563 bytes](https://vassalengine.org/files/gh/b7bc7708d94c83ec6c1b700262d697f620f16087) |

<pre>

Commands & Colors Ancients v4.2a06 [Epic] 3.5.8

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.Deck.getOrderedPieces()" because the return value of "VASSAL.build.module.map.DrawPile.getDeck()" is null
 at VASSAL.counters.GlobalCommand.apply(GlobalCommand.java:336)
 at VASSAL.counters.CounterGlobalKeyCommand.apply(CounterGlobalKeyCommand.java:272)
 at VASSAL.counters.CounterGlobalKeyCommand.myKeyEvent(CounterGlobalKeyCommand.java:161)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:486)
</pre>

**Comment by Cattlesquat** [comment] 2021-10-24 00:54
Dupe of #10561

**Closed by Cattlesquat** 2021-10-24 00:54 UTC
Labels: ABR
