### ISSUE TITLE
[Twilight Struggle 3.1] RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13062] opened 2024-01-13 12:58 UTC
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter | pierre.cuvilliers@gmail.com |
| Error Log | [15115 bytes](https://vassalengine.org/files/gh/920ec288f2efea4743f9fb86c50c445ce0c37d52) |

<pre>TRrying to open Twilight Struggle 3.1.2 vmod

Twilight Struggle 3.1 v3.1.2 3.7.7

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment] 2024-01-15 10:12
Duplicate of #11874

**Closed by BrentEaston** 2024-01-15 10:12 UTC
Labels: ABR
