### ISSUE TITLE
[????????] NullPointerException: Cannot invoke "String.length()" because "text" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13441] opened 2024-07-03 18:14 UTC
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [13960 bytes](https://vassalengine.org/files/gh/518c9bb7a17490fc0f2cacc8a5b08fbc09ebcfe7) |

<pre>

???????? v0.0 3.7.12

java.lang.NullPointerException: Cannot invoke "String.length()" because "text" is null
 at java.desktop/javax.swing.colorchooser.ValueFormatter$1.replace(ValueFormatter.java:63)
 at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:691)
 at java.desktop/javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1335)
 at java.desktop/javax.swing.text.JTextComponent.replaceInputMethodText(JTextComponent.java:4836)
</pre>

**Comment by BrentEaston** [comment] 2024-07-15 23:18
Duplicate of #12586

**Closed by BrentEaston** 2024-07-15 23:18 UTC
Labels: ABR
