### ISSUE TITLE
[VASL] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12527] opened 2023-08-05 20:53 UTC
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | greenmonstergames@gmail.com |
| Error Log | [22826 bytes](https://vassalengine.org/files/gh/6e3fa96896c0db75a587cc154eb2e5e13aada92b) |

<pre>Tried to lay overlay Be2 on the map. Repeated it a second time, both times same result. Boards go away as well.			

VASL v6.6.6 3.6.19

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardPicker.Overlay.bounds()" because "this.overlay" is null
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment] 2023-08-06 23:24
Duplicate of #12494

**Closed by BrentEaston** 2023-08-06 23:24 UTC
Labels: ABR
