### ISSUE TITLE
ExecutionException: java.io.IOException: failed to start child process

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13295] opened 2024-04-27 06:32 UTC
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter |  |
| Error Log | [12119 bytes](https://vassalengine.org/files/gh/71df3ddffb7b16857b25d79c19b76c59a69d7f05) |

<pre>6

3.7.10

java.util.concurrent.ExecutionException: java.io.IOException: failed to start child process
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:517)
</pre>

**Comment by BrentEaston** [comment] 2024-07-16 06:23
Duplicate of #12346

**Closed by BrentEaston** 2024-07-16 06:23 UTC
Labels: ABR
