### ISSUE TITLE
[Empire of the Sun (2nd Edition)] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13095] opened 2024-01-23 22:52 UTC
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter |  |
| Error Log | [260140 bytes](https://vassalengine.org/files/gh/69feac0c9fcb99d95d7caf74a971798bfef7caa8) |

<pre>

Empire of the Sun (2nd Edition) v5.11 3.7.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment] 2024-01-24 08:00
Duplicate of #5813

**Closed by BrentEaston** 2024-01-24 08:00 UTC
Labels: ABR
